Unity Modules: TransformHistory Class Reference
TransformHistory Class Reference
Implements a resample-able transform history.
Classes
struct TransformData
Public Member Functions
TransformHistory (int capacity=32)
void UpdateDelay (Pose curPose, long timestamp)
void SampleTransform (long timestamp, out Vector3 delayedPos, out Quaternion delayedRot)
Public Attributes
RingBuffer< TransformData > history
Detailed Description
Implements a resample-able transform history.
Constructor & Destructor Documentation
TransformHistory (int capacity = 32)
Member Function Documentation
void SampleTransform (long timestamp, out Vector3 delayedPos, out Quaternion delayedRot)
Referenced by LeapXRServiceProvider.GetWarpedMatrix(), and LeapXRServiceProvider.Update().
void UpdateDelay (Pose curPose, long timestamp)
Referenced by LeapXRServiceProvider.Update().
Member Data Documentation
RingBuffer<TransformData> history
Referenced by LeapXRServiceProvider.GetWarpedMatrix().