Unity Modules: SkeletalFinger Class Reference
SkeletalFinger Class Reference
Public Member Functions
override void InitFinger ()
override void UpdateFinger ()
void SetLeapHand (Hand hand)
Hand GetLeapHand ()
Finger GetLeapFinger ()
Vector3 GetTipPosition ()
Vector3 GetJointPosition (int joint)
Ray GetRay ()
Vector3 GetBoneCenter (int bone_type)
Vector3 GetBoneDirection (int bone_type)
Quaternion GetBoneRotation (int bone_type)
float GetBoneLength (int bone_type)
float GetBoneWidth (int bone_type)
float GetFingerJointStretchMecanim (int joint_type)
float GetFingerJointSpreadMecanim ()
Public Attributes
const int NUM_BONES
const int NUM_JOINTS
Finger.FingerType fingerType
Transform[] bones
Transform[] joints
Protected Member Functions
void SetPositions ()
Protected Attributes
Hand hand_
Finger finger_
Detailed Description
A finger object consisting of discrete, component parts for each bone.
The graphic objects can include both bones and joints, but both are optional.
Member Function Documentation
Vector3 GetBoneCenter (int bone_type) inherited
Returns the center of the given bone on the finger
Referenced by SkeletalFinger.SetPositions(), and RigidFinger.UpdateFinger().
Vector3 GetBoneDirection (int bone_type) inherited
Returns the direction the given bone is facing on the finger
Referenced by FingerModel.GetRay().
float GetBoneLength (int bone_type) inherited
Returns the length of the finger bone.
Referenced by RigidFinger.UpdateFinger().
Quaternion GetBoneRotation (int bone_type) inherited
Returns the rotation quaternion of the given bone
Referenced by FingerModel.GetFingerJointSpreadMecanim(), FingerModel.GetFingerJointStretchMecanim(), PolyFinger.GetJointRotation(), SkeletalFinger.SetPositions(), RigidFinger.UpdateFinger(), and RiggedFinger.UpdateFinger().
float GetBoneWidth (int bone_type) inherited
Returns the width of the finger bone.
Referenced by RigidFinger.UpdateFinger().
float GetFingerJointSpreadMecanim () inherited
Returns Mecanim spread angle, which only applies to joint_type = 0 NOTE: Positive spread is towards thumb for index and middle, but is in the opposite direction for the ring and pinky. For the thumb negative spread rotates the thumb in to the palm.
float GetFingerJointStretchMecanim (int joint_type) inherited
Returns Mecanim stretch angle in the range (-180, +180] NOTE: Positive stretch opens the hand. For the thumb this moves it away from the palm.
Vector3 GetJointPosition (int joint) inherited
Returns the location of the given joint on the finger
Referenced by FingerModel.GetBoneDirection(), SkeletalFinger.SetPositions(), PolyFinger.UpdateCapMesh(), RiggedFinger.UpdateFinger(), and PolyFinger.UpdateMesh().
Finger GetLeapFinger () inherited
The Leap Finger object.
Hand GetLeapHand () inherited
The Leap Hand object.
Ray GetRay () inherited
Returns a ray from the tip of the finger in the direction it is pointing.
Vector3 GetTipPosition () inherited
Returns the location of the tip of the finger
Referenced by FingerModel.GetJointPosition(), and FingerModel.GetRay().
override void InitFinger () virtual
Initializes the finger bones and joints by setting their positions and rotations.
Reimplemented from FingerModel.
void SetLeapHand (Hand hand) inherited
Sets the Leap Hand and Leap Finger for this finger. Note that Leap Hand and Finger objects are recreated every frame. The parent HandModel object calls this function to set or update the underlying finger. The tracking data in the Leap objects are used to update the FingerModel.
Referenced by HandModel.SetLeapHand().
void SetPositions () protected
Referenced by SkeletalFinger.InitFinger(), and SkeletalFinger.UpdateFinger().
override void UpdateFinger () virtual
Updates the finger bones and joints by setting their positions and rotations.
Implements FingerModel.
Member Data Documentation
Transform [] bones inherited
Bones positioned and rotated by FingerModel.
Referenced by RiggedFinger.Reorientation(), SkeletalFinger.SetPositions(), RiggedFinger.SetupRiggedFinger(), RigidFinger.UpdateFinger(), and RiggedFinger.UpdateFinger().
Finger finger_ protected inherited
The Leap Finger object.
Referenced by FingerModel.GetLeapFinger().
Finger.FingerType fingerType inherited
Referenced by RiggedHand.AutoRigRiggedHand(), FingerModel.GetFingerJointSpreadMecanim(), PolyHand.InitHand(), HandModel.InitHand(), FingerModel.SetLeapHand(), RiggedFinger.SetupRiggedFinger(), LeapHandsAutoRig.StoreStartPose(), RiggedFinger.UpdateFinger(), and RiggedHand.UpdateHand().
Hand hand_ protected inherited
The Leap Hand object.
Referenced by FingerModel.GetLeapHand().
Transform [] joints inherited
Joints positioned and rotated by FingerModel.
Referenced by SkeletalFinger.SetPositions().
const int NUM_BONES inherited
The number of bones in a finger.
Referenced by PolyFinger.GetJointRotation(), PolyFinger.InitMesh(), and PolyFinger.UpdateMesh().
const int NUM_JOINTS inherited
The number of joints in a finger.
Referenced by PolyFinger.UpdateCapMesh().