Unity Modules: VectorHand Class Reference
VectorHand Class Reference
A Vector-based encoding of a Leap Hand.
Public Member Functions
VectorHand ()
VectorHand (Hand hand)
Constructs a VectorHand representation from a Leap hand. This allocates a vector array for the encoded hand data.
void Encode (Hand fromHand)
void Decode (Hand intoHand)
void ReadBytes (byte[] bytes, ref int offset)
Fills this VectorHand with data read from the provided byte array, starting at the provided offset.
void FillBytes (byte[] bytesToFill, ref int offset)
Fills the provided byte array with a compressed, 86-byte form of this VectorHand, starting at the provided offset.
void FillBytes (byte[] bytesToFill)
Fills the provided byte array with a compressed, 86-byte form of this VectorHand.
void ReadBytes (byte[] bytes, ref int offset, Hand intoHand)
Shortcut for reading a VectorHand-encoded byte representation of a Leap hand and decoding it immediately into a Hand object.
void FillBytes (byte[] bytes, ref int offset, Hand fromHand)
Shortcut for encoding a Leap hand into a VectorHand representation and compressing it immediately into a byte representation.
Static Public Member Functions
static Vector3 ToWorld (Vector3 localPoint, Vector3 localOrigin, Quaternion localRot)
Converts a local-space point to a world-space point given the local space's origin and rotation.
static Vector3 ToLocal (Vector3 worldPoint, Vector3 localOrigin, Quaternion localRot)
Converts a world-space point to a local-space point given the local space's origin and rotation.
Public Attributes
const int NUM_JOINT_POSITIONS
bool isLeft
Vector3 palmPos
Quaternion palmRot
Properties
Vector3[] jointPositions [get]
int numBytesRequired [get]
The number of bytes required to encode a VectorHand into its byte representation. The byte representation is compressed to 86 bytes.
Detailed Description
A Vector-based encoding of a Leap Hand.
You can Encode a VectorHand from a Leap hand, Decode a VectorHand into a Leap hand, convert the VectorHand to a compressed byte representation using FillBytes, and decompress back into a VectorHand using FromBytes.
Also see CurlHand for a more compressed but slightly less articulated encoding. TODO: CurlHand not yet brought in from Networking module!
Constructor & Destructor Documentation
VectorHand ()
VectorHand (Hand hand)
Constructs a VectorHand representation from a Leap hand. This allocates a vector array for the encoded hand data.
Use a pooling strategy to avoid unnecessary allocation in runtime contexts.
Member Function Documentation
void Decode (Hand intoHand)
Referenced by VectorHandTests.EncodeDecodeTest().
void Encode (Hand fromHand)
Referenced by VectorHandTests.EncodeDecodeTest().
void FillBytes (byte[] bytesToFill, ref int offset)
Fills the provided byte array with a compressed, 86-byte form of this VectorHand, starting at the provided offset.
Throws an IndexOutOfRangeException if the provided byte array doesn't have enough space (starting from the offset) to write the number of bytes required.
Referenced by VectorHandTests.EncodeDecodeTest().
void FillBytes (byte[] bytesToFill)
Fills the provided byte array with a compressed, 86-byte form of this VectorHand.
Throws an IndexOutOfRangeException if the provided byte array doesn't have enough space to write the number of bytes required (see VectorHand.BYTE_ENCODING_SIZE).
void FillBytes (byte[] bytes, ref int offset, Hand fromHand)
Shortcut for encoding a Leap hand into a VectorHand representation and compressing it immediately into a byte representation.
void ReadBytes (byte[] bytes, ref int offset)
Fills this VectorHand with data read from the provided byte array, starting at the provided offset.
Referenced by VectorHandTests.EncodeDecodeTest().
void ReadBytes (byte[] bytes, ref int offset, Hand intoHand)
Shortcut for reading a VectorHand-encoded byte representation of a Leap hand and decoding it immediately into a Hand object.
static Vector3 ToLocal (Vector3 worldPoint, Vector3 localOrigin, Quaternion localRot) static
Converts a world-space point to a local-space point given the local space's origin and rotation.
static Vector3 ToWorld (Vector3 localPoint, Vector3 localOrigin, Quaternion localRot) static
Converts a local-space point to a world-space point given the local space's origin and rotation.
Member Data Documentation
bool isLeft
const int NUM_JOINT_POSITIONS
Vector3 palmPos
Quaternion palmRot
Property Documentation
Vector3 [] jointPositions get
int numBytesRequired get
The number of bytes required to encode a VectorHand into its byte representation. The byte representation is compressed to 86 bytes.
The first byte determines chirality, the camera-local hand position uses 6 bytes, the camera-local hand rotation uses 4 bytes, and each joint position component is encoded in hand-local space using 3 bytes.
Referenced by VectorHandTests.EncodeDecodeTest().