Unity Modules: InteractionManager Class Reference
InteractionManager Class Reference
Public Member Functions
void RegisterInteractionBehaviour (IInteractionBehaviour interactionObj)
bool UnregisterInteractionBehaviour (IInteractionBehaviour interactionObj)
Returns true if the Interaction Behaviour was registered with this manager; otherwise returns false. The manager is guaranteed not to have the Interaction Behaviour registered after calling this method.
bool IsBehaviourRegistered (IInteractionBehaviour interactionObj)
void TransformAheadByFixedUpdate (Vector3 position, Quaternion rotation, out Vector3 newPosition, out Quaternion newRotation)
Transforms a position and rotation ahead by one FixedUpdate based on the prior motion of the InteractionManager.
void TransformAheadByFixedUpdate (Vector3 position, out Vector3 newPosition)
Transforms a position ahead by one FixedUpdate based on the prior motion (position AND rotation) of the InteractionManager.
int GetInteractionLayerMask ()
Returns a layer mask containing all layers that might contain interaction objects.
void OnDrawRuntimeGizmos (RuntimeGizmoDrawer drawer)
Public Attributes
float hoverActivationRadius
float touchActivationRadius
Action OnGraphicalUpdate
Action OnPrePhysicalUpdate
Action OnPostPhysicalUpdate
List< PhysicsUtility.SoftContact > _softContacts
Stores data for implementing Soft Contact for interaction controllers.
Dictionary< Rigidbody, PhysicsUtility.Velocities > _softContactOriginalVelocities
Stores data for implementing Soft Contact for interaction controllers.
Protected Member Functions
void generateAutomaticLayers ()
Protected Attributes
bool _autoGenerateLayers
SingleLayer _templateLayer
SingleLayer _interactionLayer
SingleLayer _interactionNoContactLayer
SingleLayer _contactBoneLayer
Properties
ReadonlyHashSet< InteractionController > interactionControllers [get]
Gets the list of interaction controllers managed by this InteractionManager.
bool autoGenerateLayers [get]
Gets whether auto-generate layers was enabled for this Interaction Manager.
SingleLayer templateLayer [get]
SingleLayer interactionLayer [get]
SingleLayer interactionNoContactLayer [get]
SingleLayer contactBoneLayer [get]
float WorldHoverActivationRadius [get]
Interaction objects further than this distance from a given controller's hover point will not be considered for any hover interactions with that controller.
float WorldTouchActivationRadius [get]
Interaction objects further than this distance from a given controller's hover point will not be considered for any contact or grasping interactions with that controller.
float SimulationScale [get]
A scale that can be used to appropriately transform distances that otherwise expect one Unity unit to correspond to one meter.
ReadonlyHashSet< IInteractionBehaviour > interactionObjects [get]
Gets a set of all interaction objects currently registered with this Interaction Manager.
Dictionary< Rigidbody, IInteractionBehaviour > interactionObjectBodies [get]
Maps a Rigidbody to its attached interaction object, if the Rigidbody is part of and interaction object.
Dictionary< Rigidbody, ContactBone > contactBoneBodies [get]
Maps a Rigidbody to its attached ContactBone, if the Rigidbody is part of an interaction controller.
static InteractionManager instance [get, set]
Often, only one InteractionManager is necessary per Unity scene. This property will contain that InteractionManager as soon as its Awake() method is called. Using more than one InteractionManager is valid, but be sure to assign any InteractionBehaviour's desired manager appropriately.
bool hasMovingFrameOfReference [get]
Member Function Documentation
void generateAutomaticLayers () protected
int GetInteractionLayerMask ()
Returns a layer mask containing all layers that might contain interaction objects.
Referenced by HeuristicGrabClassifier.FixedUpdateClassifierHandState(), HeuristicGrabClassifier.HeuristicGrabClassifier(), and InteractionController.SwapGrasp().
bool IsBehaviourRegistered (IInteractionBehaviour interactionObj)
void OnDrawRuntimeGizmos (RuntimeGizmoDrawer drawer)
Implements IRuntimeGizmoComponent.
void RegisterInteractionBehaviour (IInteractionBehaviour interactionObj)
Referenced by InteractionBehaviour.OnEnable().
void TransformAheadByFixedUpdate (Vector3 position, Quaternion rotation, out Vector3 newPosition, out Quaternion newRotation)
Transforms a position and rotation ahead by one FixedUpdate based on the prior motion of the InteractionManager.
This method is used to support having the player in a moving frame of reference.
void TransformAheadByFixedUpdate (Vector3 position, out Vector3 newPosition)
Transforms a position ahead by one FixedUpdate based on the prior motion (position AND rotation) of the InteractionManager.
This method is used to support having the player in a moving frame of reference.
bool UnregisterInteractionBehaviour (IInteractionBehaviour interactionObj)
Returns true if the Interaction Behaviour was registered with this manager; otherwise returns false. The manager is guaranteed not to have the Interaction Behaviour registered after calling this method.
Member Data Documentation
bool _autoGenerateLayers protected
SingleLayer _contactBoneLayer protected
SingleLayer _interactionLayer protected
SingleLayer _interactionNoContactLayer protected
Dictionary<Rigidbody, PhysicsUtility.Velocities> _softContactOriginalVelocities
Stores data for implementing Soft Contact for interaction controllers.
List<PhysicsUtility.SoftContact> _softContacts
Stores data for implementing Soft Contact for interaction controllers.
SingleLayer _templateLayer protected
float hoverActivationRadius
Action OnGraphicalUpdate
Action OnPostPhysicalUpdate
Action OnPrePhysicalUpdate
float touchActivationRadius
Property Documentation
bool autoGenerateLayers get
Gets whether auto-generate layers was enabled for this Interaction Manager.
Dictionary<Rigidbody, ContactBone> contactBoneBodies get
Maps a Rigidbody to its attached ContactBone, if the Rigidbody is part of an interaction controller.
SingleLayer contactBoneLayer get
bool hasMovingFrameOfReference get
InteractionManager instance static get set
Often, only one InteractionManager is necessary per Unity scene. This property will contain that InteractionManager as soon as its Awake() method is called. Using more than one InteractionManager is valid, but be sure to assign any InteractionBehaviour's desired manager appropriately.
By default, this static property contains the first InteractionManager that has had its Awake() method called in the current scene. If an InteractionBehaviourBase does not have a non-null interactionManager by the time it has Start() called, it will default to using the InteractionManager referenced here.
If you have multiple InteractionManagers in your scene, you should be sure to assign InteractionBehaviours' managers appropriately. If you instantiate an InteractionBehaviour at runtime, you should assign its InteractionManager right after you instantiate it.
Referenced by InteractionBehaviourEditor.OnEnable(), InteractionBehaviour.OnEnable(), and InteractionController.Start().
ReadonlyHashSet<InteractionController> interactionControllers get
Gets the list of interaction controllers managed by this InteractionManager.
SingleLayer interactionLayer get
SingleLayer interactionNoContactLayer get
Dictionary<Rigidbody, IInteractionBehaviour> interactionObjectBodies get
Maps a Rigidbody to its attached interaction object, if the Rigidbody is part of and interaction object.
Referenced by InteractionController.SwapGrasp().
ReadonlyHashSet<IInteractionBehaviour> interactionObjects get
Gets a set of all interaction objects currently registered with this Interaction Manager.
float SimulationScale get
A scale that can be used to appropriately transform distances that otherwise expect one Unity unit to correspond to one meter.
Referenced by HeuristicGrabClassifier.FillClassifier(), HeuristicGrabClassifier.FixedUpdateClassifierHandState(), and NonKinematicGraspedMovement.MoveTo().
SingleLayer templateLayer get
float WorldHoverActivationRadius get
Interaction objects further than this distance from a given controller's hover point will not be considered for any hover interactions with that controller.
float WorldTouchActivationRadius get
Interaction objects further than this distance from a given controller's hover point will not be considered for any contact or grasping interactions with that controller.