Unity Modules: HandModelBase Class Reference
HandModelBase Class Reference abstract
Public Member Functions
virtual void InitHand ()
virtual void BeginHand ()
abstract void UpdateHand ()
virtual void FinishHand ()
abstract Hand GetLeapHand ()
abstract void SetLeapHand (Hand hand)
virtual bool SupportsEditorPersistence ()
Returns whether or not this hand model supports editor persistence. This is false by default and must be opt-in by a developer making their own hand model script if they want editor persistence.
Public Attributes
HandModelManager.ModelGroup group
Properties
bool IsTracked [get]
abstract Chirality Handedness [get, set]
abstract ModelType HandModelType [get]
Events
Action OnBegin
Action OnFinish
Member Function Documentation
virtual void BeginHand () virtual
Reimplemented in CapsuleHand.
Referenced by HandRepresentation.AddModel().
virtual void FinishHand () virtual
Referenced by HandRepresentation.RemoveModel().
abstract Hand GetLeapHand () pure virtual
Implemented in HandModel, CapsuleHand, MinimalHand, and DebugHand.
Referenced by HandRepresentation.AddModel(), PinchDetector.ensureUpToDate(), HandModelBase.FinishHand(), and HandModelManager.GetHandModel< T >().
virtual void InitHand () virtual
Reimplemented in HandModel, CapsuleHand, RiggedHand, MinimalHand, DebugHand, PolyHand, and RigidHand.
Referenced by HandRepresentation.AddModel().
abstract void SetLeapHand (Hand hand) pure virtual
Implemented in HandModel, CapsuleHand, MinimalHand, and DebugHand.
Referenced by HandRepresentation.AddModel(), and HandModelBase.FinishHand().
virtual bool SupportsEditorPersistence () virtual
Returns whether or not this hand model supports editor persistence. This is false by default and must be opt-in by a developer making their own hand model script if they want editor persistence.
Reimplemented in CapsuleHand, DebugHand, PolyHand, RiggedHand, RigidHand, and MinimalHand.
abstract void UpdateHand () pure virtual
Implemented in HandModel, CapsuleHand, RiggedHand, MinimalHand, DebugHand, PolyHand, SkeletalHand, and RigidHand.
Referenced by HandRepresentation.AddModel(), and HandModelBase.BeginHand().
Member Data Documentation
HandModelManager.ModelGroup group
Referenced by HandModelManager.MakeHandRepresentation().
Property Documentation
abstract Chirality Handedness get set
Referenced by HandModelManager.ReturnToPool().
abstract ModelType HandModelType get
Referenced by HandModelManager.ReturnToPool().
bool IsTracked get
Referenced by PinchDetector.ensureUpToDate().
Event Documentation
Action OnBegin
Referenced by HandTransitionBehavior.Awake(), HandModelBase.BeginHand(), and HandTransitionBehavior.OnDestroy().
Action OnFinish
Referenced by HandTransitionBehavior.Awake(), HandModelBase.FinishHand(), and HandTransitionBehavior.OnDestroy().