Unity Modules: PalmDirectionDetector Class Reference
PalmDirectionDetector Class Reference
Public Member Functions
virtual void Activate ()
virtual void Deactivate ()
Public Attributes
float Period
HandModelBase HandModel
PointingType PointingType
Vector3 PointingDirection
Transform TargetObject
float OnAngle
float OffAngle
bool ShowGizmos
UnityEvent OnActivate
UnityEvent OnDeactivate
Protected Attributes
Color OnColor
Color OffColor
Color LimitColor
Color DirectionColor
Color NormalColor
Properties
bool IsActive [get]
Detailed Description
Detects whether the palm of the hand is pointing toward the specified direction. The detector activates when the palm direction is within OnAngle degrees of the desired direction and deactivates when it becomes more than OffAngle degrees.
Directions can be specified relative to the global frame of reference, relative to the camera frame of reference, or using a combination of the two – relative to the camera direction in the x-z plane, but not changing relative to the horizon.
You can alternatively specify a target game object.
If added to a HandModelBase instance or one of its children, this detector checks the palm direction at the interval specified by the Period variable. You can also specify which hand model to observe explicitly by setting handModel in the Unity editor or in code.
Since
4.1.2
Member Function Documentation
virtual void Activate () virtual inherited
Invoked when this detector activates. Subclasses must call this function when the detector's conditions become true.
Since
4.1.2
Referenced by AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
virtual void Deactivate () virtual inherited
Invoked when this detector deactivates. Subclasses must call this function when the detector's conditions change from true to false.
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
Member Data Documentation
Color DirectionColor protected inherited
Referenced by AbstractHoldDetector.changeState().
HandModelBase HandModel
The HandModelBase instance to observe. Set automatically if not explicitly set in the editor.
Since
4.1.2
Color LimitColor protected inherited
Color NormalColor protected inherited
Referenced by AbstractHoldDetector.changeState().
float OffAngle
The turn-off angle. The detector deactivates when the palm points more than this many degrees away from the target direction. The off angle must be larger than the on angle.
Since
4.1.2
Color OffColor protected inherited
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnActivate inherited
Dispatched when the detector activates (becomes true).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
float OnAngle
The turn-on angle. The detector activates when the palm points within this many degrees of the target direction.
Since
4.1.2
Color OnColor protected inherited
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnDeactivate inherited
Dispatched when the detector deactivates (becomes false).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
float Period
The interval at which to check palm direction.
Since
4.1.2
Vector3 PointingDirection
The target direction as interpreted by the PointingType setting. Ignored when Pointingtype is "AtTarget."
Since
4.1.2
PointingType PointingType
Specifies how to interprete the direction specified by PointingDirection.
RelativeToCamera – the target direction is defined relative to the camera's forward vector, i.e. (0, 0, 1) is the cmaera's local forward direction.
RelativeToHorizon – the target direction is defined relative to the camera's forward vector, except that it does not change with pitch.
RelativeToWorld – the target direction is defined as a global direction that does not change with camera movement. For example, (0, 1, 0) is always world up, no matter which way the camera is pointing.
AtTarget – a target object is used as the pointing direction (The specified PointingDirection is ignored).
In VR scenes, RelativeToHorizon with a direction of (0, 0, 1) for camera forward and RelativeToWorld with a direction of (0, 1, 0) for absolute up, are often the most useful settings.
Since
4.1.2
bool ShowGizmos
Whether to draw the detector's Gizmos for debugging. (Not every detector provides gizmos.)
Since
4.1.2
Transform TargetObject
The object to point at when the PointingType is "AtTarget." Ignored otherwise.
Property Documentation
bool IsActive get inherited
The current detector state.
Since
4.1.2
Referenced by Detector.Activate(), AbstractHoldDetector.changeState(), Detector.Deactivate(), PinchDetector.ensureUpToDate(), and ProximityDetector.OnValidate().