Unity Modules: LeapImageRetriever.EyeTextureData Class Reference
LeapImageRetriever.EyeTextureData Class Reference
Public Member Functions
EyeTextureData ()
bool CheckStale (Image image)
void MarkStale ()
void Reconstruct (Image image)
void UpdateTextures (Image image)
Static Public Member Functions
static void ResetGlobalShaderValues ()
Public Attributes
readonly LeapTextureData TextureData
readonly LeapDistortionData Distortion
Constructor & Destructor Documentation
EyeTextureData ()
Member Function Documentation
bool CheckStale (Image image)
Referenced by LeapImageRetriever.EyeTextureData.UpdateTextures().
void MarkStale ()
Referenced by LeapImageRetriever.ApplyGammaCorrectionValues().
void Reconstruct (Image image)
Referenced by LeapImageRetriever.EyeTextureData.UpdateTextures().
static void ResetGlobalShaderValues () static
Referenced by LeapImageRetriever.EyeTextureData.UpdateTextures().
void UpdateTextures (Image image)
Referenced by LeapImageRetriever.EyeTextureData.UpdateTextures().
Member Data Documentation
readonly LeapDistortionData Distortion
readonly LeapTextureData TextureData