Unity Modules: Connection Class Reference
Connection Class Reference
Public Member Functions
void Dispose ()
void Start ()
void Stop ()
UInt64 GetInterpolatedFrameSize (Int64 time)
void GetInterpolatedFrame (Frame toFill, Int64 time)
void GetInterpolatedFrameFromTime (Frame toFill, Int64 time, Int64 sourceTime)
Frame GetInterpolatedFrame (Int64 time)
void GetInterpolatedHeadPose (ref LEAP_HEAD_POSE_EVENT toFill, Int64 time)
LEAP_HEAD_POSE_EVENT GetInterpolatedHeadPose (Int64 time)
void GetInterpolatedLeftRightTransform (Int64 time, Int64 sourceTime, Int64 leftId, Int64 rightId, out LeapTransform leftTransform, out LeapTransform rightTransform)
void SetPolicy (Controller.PolicyFlag policy)
void ClearPolicy (Controller.PolicyFlag policy)
bool IsPolicySet (Controller.PolicyFlag policy)
Gets the active setting for a specific policy.
uint GetConfigValue (string config_key)
uint SetConfigValue< T > (string config_key, T value)
Vector PixelToRectilinear (Image.CameraType camera, Vector pixel)
Vector RectilinearToPixel (Image.CameraType camera, Vector ray)
void TelemetryProfiling (ref LEAP_TELEMETRY_DATA telemetryData)
void GetPointMapping (ref PointMapping pm)
Static Public Member Functions
static Connection GetConnection (int connectionKey=0)
Public Attributes
EventHandler< ConnectionLostEventArgs > LeapConnectionLost
EventHandler< DeviceEventArgs > LeapDevice
EventHandler< DeviceEventArgs > LeapDeviceLost
EventHandler< DeviceFailureEventArgs > LeapDeviceFailure
EventHandler< PolicyEventArgs > LeapPolicyChange
EventHandler< FrameEventArgs > LeapFrame
EventHandler< InternalFrameEventArgs > LeapInternalFrame
EventHandler< LogEventArgs > LeapLogEvent
EventHandler< SetConfigResponseEventArgs > LeapConfigResponse
EventHandler< ConfigChangeEventArgs > LeapConfigChange
EventHandler< DistortionEventArgs > LeapDistortionChange
EventHandler< DroppedFrameEventArgs > LeapDroppedFrame
EventHandler< ImageEventArgs > LeapImage
EventHandler< PointMappingChangeEventArgs > LeapPointMappingChange
EventHandler< HeadPoseEventArgs > LeapHeadPoseChange
Action< BeginProfilingForThreadArgs > LeapBeginProfilingForThread
Action< EndProfilingForThreadArgs > LeapEndProfilingForThread
Action< BeginProfilingBlockArgs > LeapBeginProfilingBlock
Action< EndProfilingBlockArgs > LeapEndProfilingBlock
Protected Member Functions
virtual void Dispose (bool disposing)
Properties
int ConnectionKey [get]
CircularObjectBuffer< LEAP_TRACKING_EVENT > Frames [get, set]
SynchronizationContext EventContext [get, set]
EventHandler< LeapEventArgs > LeapInit
EventHandler< ConnectionEventArgs > LeapConnection
bool IsServiceConnected [get]
Reports whether your application has a connection to the Leap Motion daemon/service. Can be true even if the Leap Motion hardware is not available.
DeviceList Devices [get]
The list of currently attached and recognized Leap Motion controller devices.
FailedDeviceList FailedDevices [get]
Member Function Documentation
void ClearPolicy (Controller.PolicyFlag policy)
Referenced by Controller.ClearPolicy().
void Dispose ()
Referenced by Connection.Dispose(), and Connection.Start().
virtual void Dispose (bool disposing) protected virtual
uint GetConfigValue (string config_key)
Referenced by Config.Get< T >().
static Connection GetConnection (int connectionKey = 0) static
Referenced by Config.Config(), Controller.Controller(), Image.PixelToRectilinear(), and Image.RectilinearToPixel().
void GetInterpolatedFrame (Frame toFill, Int64 time)
Referenced by Connection.GetInterpolatedFrame(), and Controller.GetInterpolatedFrame().
Frame GetInterpolatedFrame (Int64 time)
void GetInterpolatedFrameFromTime (Frame toFill, Int64 time, Int64 sourceTime)
Referenced by Controller.GetInterpolatedFrameFromTime().
UInt64 GetInterpolatedFrameSize (Int64 time)
Referenced by Connection.GetInterpolatedFrame(), Connection.GetInterpolatedFrameFromTime(), and Connection.GetInterpolatedLeftRightTransform().
void GetInterpolatedHeadPose (ref LEAP_HEAD_POSE_EVENT toFill, Int64 time)
Referenced by Connection.GetInterpolatedHeadPose(), and Controller.GetInterpolatedHeadPose().
LEAP_HEAD_POSE_EVENT GetInterpolatedHeadPose (Int64 time)
void GetInterpolatedLeftRightTransform (Int64 time, Int64 sourceTime, Int64 leftId, Int64 rightId, out LeapTransform leftTransform, out LeapTransform rightTransform)
Referenced by Controller.GetInterpolatedLeftRightTransform().
void GetPointMapping (ref PointMapping pm)
Referenced by Controller.GetPointMapping().
bool IsPolicySet (Controller.PolicyFlag policy)
Gets the active setting for a specific policy.
Keep in mind that setting a policy flag is asynchronous, so changes are not effective immediately after calling setPolicyFlag(). In addition, a policy request can be declined by the user. You should always set the policy flags required by your application at startup and check that the policy change request was successful after an appropriate interval.
If the controller object is not connected to the Leap Motion software, then the default state for the selected policy is returned.
Since
2.1.6
Referenced by Controller.IsPolicySet().
Vector PixelToRectilinear (Image.CameraType camera, Vector pixel)
Referenced by Image.PixelToRectilinear().
Vector RectilinearToPixel (Image.CameraType camera, Vector ray)
Referenced by Image.RectilinearToPixel().
uint SetConfigValue< T > (string config_key, T value)
Type Constraints
T : IConvertible
void SetPolicy (Controller.PolicyFlag policy)
Referenced by Controller.SetPolicy().
void Start ()
Referenced by Controller.Controller(), and Controller.StartConnection().
void Stop ()
Referenced by Connection.Dispose(), and Controller.StopConnection().
void TelemetryProfiling (ref LEAP_TELEMETRY_DATA telemetryData)
Referenced by Controller.TelemetryProfiling().
Member Data Documentation
Action<BeginProfilingBlockArgs> LeapBeginProfilingBlock
Referenced by Connection.Stop().
Action<BeginProfilingForThreadArgs> LeapBeginProfilingForThread
Referenced by Connection.Stop().
EventHandler<ConfigChangeEventArgs> LeapConfigChange
Referenced by Config.Config().
EventHandler<SetConfigResponseEventArgs> LeapConfigResponse
Referenced by Config.Config().
EventHandler<ConnectionLostEventArgs> LeapConnectionLost
Referenced by Controller.Controller().
EventHandler<DeviceEventArgs> LeapDevice
EventHandler<DeviceFailureEventArgs> LeapDeviceFailure
EventHandler<DeviceEventArgs> LeapDeviceLost
EventHandler<DistortionEventArgs> LeapDistortionChange
EventHandler<DroppedFrameEventArgs> LeapDroppedFrame
Action<EndProfilingBlockArgs> LeapEndProfilingBlock
Referenced by Connection.Stop().
Action<EndProfilingForThreadArgs> LeapEndProfilingForThread
Referenced by Connection.Stop().
EventHandler<FrameEventArgs> LeapFrame
EventHandler<HeadPoseEventArgs> LeapHeadPoseChange
EventHandler<ImageEventArgs> LeapImage
EventHandler<InternalFrameEventArgs> LeapInternalFrame
EventHandler<LogEventArgs> LeapLogEvent
EventHandler<PointMappingChangeEventArgs> LeapPointMappingChange
EventHandler<PolicyEventArgs> LeapPolicyChange
Property Documentation
int ConnectionKey get
Referenced by Connection.Dispose().
DeviceList Devices get
The list of currently attached and recognized Leap Motion controller devices.
The Device objects in the list describe information such as the range and tracking volume.
Currently, the Leap Motion Controller only allows a single active device at a time, however there may be multiple devices physically attached and listed here. Any active device(s) are guaranteed to be listed first, however order is not determined beyond that.
Since
1.0
SynchronizationContext EventContext get set
Referenced by Controller.Controller(), Connection.GetInterpolatedLeftRightTransform(), Connection.GetPointMapping(), and Connection.Stop().
FailedDeviceList FailedDevices get
Referenced by Controller.FailedDevices().
CircularObjectBuffer<LEAP_TRACKING_EVENT> Frames get set
Referenced by Connection.Dispose(), Controller.Frame(), Controller.FrameTimestamp(), and Connection.Stop().
bool IsServiceConnected get
Reports whether your application has a connection to the Leap Motion daemon/service. Can be true even if the Leap Motion hardware is not available.
Since
1.2
EventHandler<ConnectionEventArgs> LeapConnection add remove
Referenced by Controller.Controller().
EventHandler<LeapEventArgs> LeapInit add remove
Referenced by Controller.Controller().