Unity Modules: QueryTests.QueryArg Class Reference
QueryTests.QueryArg Class Reference
Public Member Functions
QueryArg (List< int > values, int capacity)
Query< int > ToQuery ()
List< int > ToList ()
override string ToString ()
Constructor & Destructor Documentation
QueryArg (List< int > values, int capacity)
Member Function Documentation
List<int> ToList ()
Referenced by QueryTests.AllTest(), QueryTests.AnyTest(), QueryTests.AverageTest(), QueryTests.ConcatTest(), QueryTests.ContainsTest(), QueryTests.CountTests(), QueryTests.DistinctTest(), QueryTests.ElementAtTest(), QueryTests.FirstOrDefaultTests(), QueryTests.FirstTests(), QueryTests.FoldTest(), QueryTests.ForeachTest(), QueryTests.IndexOfTests(), QueryTests.LastTests(), QueryTests.MaxTest(), QueryTests.MinTest(), QueryTests.OrderByDescendingTest(), QueryTests.OrderByTest(), QueryTests.Repeat(), QueryTests.ReverseTest(), QueryTests.SelectManyTest(), QueryTests.SelectTest(), QueryTests.SkipTest(), QueryTests.SkipWhileTest(), QueryTests.SortDescendingTests(), QueryTests.SortTest(), QueryTests.SumTests(), QueryTests.TakeTest(), QueryTests.TakeWhileTest(), QueryTests.WhereTest(), QueryTests.WithIndicesTest(), QueryTests.WithPreviousOffsetTest(), QueryTests.WithPreviousTest(), and QueryTests.ZipTest().
Query<int> ToQuery ()
Referenced by QueryTests.AllTest(), QueryTests.AnyTest(), QueryTests.AverageTest(), QueryTests.ConcatTest(), QueryTests.ContainsTest(), QueryTests.CountTests(), QueryTests.DistinctTest(), QueryTests.ElementAtTest(), QueryTests.FirstOrDefaultTests(), QueryTests.FirstTests(), QueryTests.FoldTest(), QueryTests.ForeachTest(), QueryTests.IndexOfTests(), QueryTests.LastTests(), QueryTests.MaxTest(), QueryTests.MinTest(), QueryTests.MultiFirstTest(), QueryTests.MultiForeachTest(), QueryTests.OrderByDescendingTest(), QueryTests.OrderByTest(), QueryTests.Repeat(), QueryTests.ReverseTest(), QueryTests.SelectManyTest(), QueryTests.SelectTest(), QueryTests.SkipTest(), QueryTests.SkipWhileTest(), QueryTests.SortDescendingTests(), QueryTests.SortTest(), QueryTests.SumTests(), QueryTests.TakeTest(), QueryTests.TakeWhileTest(), QueryTests.WhereTest(), QueryTests.WithIndicesTest(), QueryTests.WithPreviousOffsetTest(), QueryTests.WithPreviousTest(), and QueryTests.ZipTest().
override string ToString ()