Unity Modules: KabschGraspedPose.PosePointCollection Class Reference
KabschGraspedPose.PosePointCollection Class Reference
Public Member Functions
void SetWorldPosition (int index, Vector3 worldPosition)
Vector3 GetLocalPosition (int index)
Static Public Member Functions
static PosePointCollection Create (Vector3 position, Quaternion rotation)
static void Return (PosePointCollection posePointCollection)
Member Function Documentation
static PosePointCollection Create (Vector3 position, Quaternion rotation) static
Referenced by KabschGraspedPose.AddController().
Vector3 GetLocalPosition (int index)
Referenced by KabschGraspedPose.GetGraspedPosition().
static void Return (PosePointCollection posePointCollection) static
Referenced by KabschGraspedPose.ClearControllers(), and KabschGraspedPose.RemoveController().
void SetWorldPosition (int index, Vector3 worldPosition)