Unity Modules: DeviceList Class Reference
DeviceList Class Reference
The DeviceList class represents a list of Device objects.
Public Member Functions
DeviceList ()
Constructs an empty list of devices.
Device FindDeviceByHandle (IntPtr deviceHandle)
For internal use only.
void AddOrUpdate (Device device)
For internal use only.
Properties
Device ActiveDevice [get]
The device that is currently streaming tracking data. If no streaming devices are found, returns null
bool IsEmpty [get]
Reports whether the list is empty.
Detailed Description
The DeviceList class represents a list of Device objects.
Get a DeviceList object by calling Controller.Devices().
Since
1.0
Constructor & Destructor Documentation
DeviceList ()
Constructs an empty list of devices.
Since
1.0
Member Function Documentation
void AddOrUpdate (Device device)
For internal use only.
Referenced by Connection.GetInterpolatedLeftRightTransform().
Device FindDeviceByHandle (IntPtr deviceHandle)
For internal use only.
Referenced by DeviceList.AddOrUpdate(), and Connection.GetInterpolatedLeftRightTransform().
Property Documentation
Device ActiveDevice get
The device that is currently streaming tracking data. If no streaming devices are found, returns null
bool IsEmpty get
Reports whether the list is empty.
Since
1.0
Referenced by DeviceTests.DeviceList_isEmpty().