Unity Modules: TweenRunner Class Reference
TweenRunner Class Reference
Public Member Functions
void ScheduleForRecycle (TweenInstance instance)
void AddTween (TweenInstance instance)
void RemoveTween (TweenInstance instance)
Properties
static TweenRunner instance [get]
Member Function Documentation
void AddTween (TweenInstance instance)
Referenced by Tween.Play().
void RemoveTween (TweenInstance instance)
Referenced by Tween.Pause(), and TweenInstance.Step().
void ScheduleForRecycle (TweenInstance instance)
Referenced by Tween.Release().
Property Documentation
TweenRunner instance static get
Referenced by Tween.Pause(), Tween.Play(), and Tween.Release().