Unity Modules: LeapXRServiceProvider Class Reference
LeapXRServiceProvider Class Reference
The LeapXRServiceProvider expands on the standard LeapServiceProvider to account for the offset of the Leap device with respect to the attached HMD and warp tracked hand positions based on the motion of the headset to account for the differing latencies of the two tracking systems.
Public Types
Public Member Functions
float CalculatePhysicsExtrapolation ()
Controller GetLeapController ()
Returns the Leap Controller instance.
bool IsConnected ()
Returns true if the Leap Motion hardware is plugged in and this application is connected to the Leap Motion service.
void RetransformFrames ()
Retransforms hand data from Leap space to the space of the Unity transform. This is only necessary if you're moving the LeapServiceProvider around in a custom script and trying to access Hand data from it directly afterward.
void CopySettingsToLeapXRServiceProvider (LeapXRServiceProvider leapXRServiceProvider)
Copies property settings from this LeapServiceProvider to the target LeapXRServiceProvider where applicable. Does not modify any XR-specific settings that only exist on the LeapXRServiceProvider.
Public Attributes
long imageTimeStamp
TestHandPose editTimePose
Protected Member Functions
override void Reset ()
virtual void OnValidate ()
virtual void OnEnable ()
virtual void OnDisable ()
override void Start ()
override void Update ()
override long CalculateInterpolationTime (bool endOfFrame=false)
override void initializeFlags ()
Initializes the Leap Motion policy flags. The POLICY_OPTIMIZE_HMD flag improves tracking for head-mounted devices.
override void transformFrame (Frame source, Frame dest)
void resetShaderTransforms ()
Resets shader globals for the Hand transforms.
virtual LeapTransform GetWarpedMatrix (long timestamp, bool updateTemporalCompensation=true)
void transformHands (ref LeapTransform LeftHand, ref LeapTransform RightHand)
void OnPreCullHandTransforms (Camera camera)
virtual void Awake ()
virtual void FixedUpdate ()
virtual void OnDestroy ()
virtual void OnApplicationPause (bool isPaused)
virtual void OnApplicationQuit ()
void createController ()
Creates an instance of a Controller, initializing its policy flags and subscribing to its connection event.
void destroyController ()
Stops the connection for the existing instance of a Controller, clearing old policy flags and resetting the Controller to null.
bool checkConnectionIntegrity ()
Checks whether this provider is connected to a service; If it is not, attempt to reconnect at regular intervals for MAX_RECONNECTION_ATTEMPTS
void onHandControllerConnect (object sender, LeapEventArgs args)
void DispatchUpdateFrameEvent (Frame frame)
void DispatchFixedFrameEvent (Frame frame)
Protected Attributes
bool _updateHandInPrecull
TransformHistory transformHistory
bool manualUpdateHasBeenCalledSinceUpdate
Vector3 warpedPosition
Quaternion warpedRotation
Matrix4x4[] _transformArray
const double NS_TO_S
Converts nanoseconds to seconds.
const double S_TO_NS
Converts seconds to nanoseconds.
const string HAND_ARRAY_GLOBAL_NAME
The transform array used for late-latching.
const int MAX_RECONNECTION_ATTEMPTS
The maximum number of times the provider will attempt to reconnect to the service before giving up.
const int RECONNECTION_INTERVAL
The number of frames to wait between each reconnection attempt.
FrameOptimizationMode _frameOptimization
PhysicsExtrapolationMode _physicsExtrapolation
float _physicsExtrapolationTime
bool _workerThreadProfiling
bool _useInterpolation
int ExtrapolationAmount
int BounceAmount
Controller _leapController
bool _isDestroyed
SmoothedFloat _fixedOffset
SmoothedFloat _smoothedTrackingLatency
long _unityToLeapOffset
Frame _untransformedUpdateFrame
Frame _transformedUpdateFrame
Frame _untransformedFixedFrame
Frame _transformedFixedFrame
Properties
DeviceOffsetMode deviceOffsetMode [get, set]
float deviceOffsetYAxis [get, set]
float deviceOffsetZAxis [get, set]
float deviceTiltXAxis [get, set]
Transform deviceOrigin [get, set]
int warpingAdjustment [get]
bool updateHandInPrecull [get, set]
Action< Device > OnDeviceSafe
A utility event to get a callback whenever a new device is connected to the service. This callback will ALSO trigger a callback upon subscription if a device is already connected.
override Frame CurrentFrame [get]
override Frame CurrentFixedFrame [get]
Events
Action< Frame > OnUpdateFrame
Action< Frame > OnFixedFrame
Detailed Description
The LeapXRServiceProvider expands on the standard LeapServiceProvider to account for the offset of the Leap device with respect to the attached HMD and warp tracked hand positions based on the motion of the headset to account for the differing latencies of the two tracking systems.
Member Enumeration Documentation
enum DeviceOffsetMode strong
Enumerator
Default
ManualHeadOffset
Transform
enum FrameOptimizationMode strong inherited
Enumerator
None
ReuseUpdateForPhysics
ReusePhysicsForUpdate
enum PhysicsExtrapolationMode strong inherited
Enumerator
None
Auto
Manual
enum TemporalWarpingMode strong
Enumerator
Auto
Manual
Images
Off
Member Function Documentation
virtual void Awake () protected virtual inherited
override long CalculateInterpolationTime (bool endOfFrame = false) protected virtual
Reimplemented from LeapServiceProvider.
Referenced by LeapXRServiceProvider.OnPreCullHandTransforms().
float CalculatePhysicsExtrapolation () inherited
Referenced by LeapServiceProvider.FixedUpdate().
bool checkConnectionIntegrity () protected inherited
Checks whether this provider is connected to a service; If it is not, attempt to reconnect at regular intervals for MAX_RECONNECTION_ATTEMPTS
Referenced by LeapServiceProvider.Update().
void CopySettingsToLeapXRServiceProvider (LeapXRServiceProvider leapXRServiceProvider) inherited
Copies property settings from this LeapServiceProvider to the target LeapXRServiceProvider where applicable. Does not modify any XR-specific settings that only exist on the LeapXRServiceProvider.
Referenced by OldRigHierarchy.Upgrade().
void createController () protected inherited
Creates an instance of a Controller, initializing its policy flags and subscribing to its connection event.
Referenced by LeapServiceProvider.checkConnectionIntegrity(), LeapServiceProvider.GetLeapController(), and LeapServiceProvider.Start().
void destroyController () protected inherited
Stops the connection for the existing instance of a Controller, clearing old policy flags and resetting the Controller to null.
Referenced by LeapServiceProvider.checkConnectionIntegrity(), LeapServiceProvider.OnApplicationQuit(), and LeapServiceProvider.OnDestroy().
void DispatchFixedFrameEvent (Frame frame) protected inherited
Referenced by LeapServiceProvider.FixedUpdate(), and PostProcessProvider.OnValidate().
void DispatchUpdateFrameEvent (Frame frame) protected inherited
Referenced by PostProcessProvider.OnValidate(), and LeapServiceProvider.Update().
virtual void FixedUpdate () protected virtual inherited
Controller GetLeapController () inherited
Returns the Leap Controller instance.
Referenced by LeapServiceProvider.IsConnected(), and LeapImageRetriever.EyeTextureData.UpdateTextures().
virtual LeapTransform GetWarpedMatrix (long timestamp, bool updateTemporalCompensation = true) protected virtual
Referenced by LeapXRServiceProvider.transformFrame(), and LeapXRServiceProvider.transformHands().
override void initializeFlags () protected virtual
Initializes the Leap Motion policy flags. The POLICY_OPTIMIZE_HMD flag improves tracking for head-mounted devices.
Reimplemented from LeapServiceProvider.
bool IsConnected () inherited
Returns true if the Leap Motion hardware is plugged in and this application is connected to the Leap Motion service.
virtual void OnApplicationPause (bool isPaused) protected virtual inherited
virtual void OnApplicationQuit () protected virtual inherited
virtual void OnDestroy () protected virtual inherited
virtual void OnDisable () protected virtual
virtual void OnEnable () protected virtual
void onHandControllerConnect (object sender, LeapEventArgs args) protected inherited
Referenced by LeapServiceProvider.createController().
void OnPreCullHandTransforms (Camera camera) protected
Referenced by LeapXRServiceProvider.Update().
virtual void OnValidate () protected virtual
override void Reset () protected virtual
Reimplemented from LeapServiceProvider.
void resetShaderTransforms () protected
Resets shader globals for the Hand transforms.
Referenced by LeapXRServiceProvider.OnDisable(), and LeapXRServiceProvider.OnEnable().
void RetransformFrames () inherited
Retransforms hand data from Leap space to the space of the Unity transform. This is only necessary if you're moving the LeapServiceProvider around in a custom script and trying to access Hand data from it directly afterward.
override void Start () protected virtual
Reimplemented from LeapServiceProvider.
override void transformFrame (Frame source, Frame dest) protected virtual
Reimplemented from LeapServiceProvider.
void transformHands (ref LeapTransform LeftHand, ref LeapTransform RightHand) protected
Referenced by LeapXRServiceProvider.OnPreCullHandTransforms().
override void Update () protected virtual
Reimplemented from LeapServiceProvider.
Member Data Documentation
SmoothedFloat _fixedOffset protected inherited
FrameOptimizationMode _frameOptimization protected inherited
Referenced by LeapServiceProvider.CopySettingsToLeapXRServiceProvider().
bool _isDestroyed protected inherited
Controller _leapController protected inherited
Referenced by LeapXRServiceProvider.CalculateInterpolationTime(), LeapServiceProvider.GetLeapController(), LeapXRServiceProvider.initializeFlags(), LeapXRServiceProvider.OnPreCullHandTransforms(), and LeapXRServiceProvider.Update().
PhysicsExtrapolationMode _physicsExtrapolation protected inherited
Referenced by LeapServiceProvider.CopySettingsToLeapXRServiceProvider().
float _physicsExtrapolationTime protected inherited
Referenced by LeapServiceProvider.CalculatePhysicsExtrapolation(), and LeapServiceProvider.CopySettingsToLeapXRServiceProvider().
SmoothedFloat _smoothedTrackingLatency protected inherited
Referenced by LeapXRServiceProvider.CalculateInterpolationTime().
Matrix4x4 [] _transformArray protected
Frame _transformedFixedFrame protected inherited
Frame _transformedUpdateFrame protected inherited
long _unityToLeapOffset protected inherited
Referenced by LeapServiceProvider.FixedUpdate().
Frame _untransformedFixedFrame protected inherited
Frame _untransformedUpdateFrame protected inherited
bool _updateHandInPrecull protected
bool _useInterpolation protected inherited
bool _workerThreadProfiling protected inherited
Referenced by LeapServiceProvider.CopySettingsToLeapXRServiceProvider().
int BounceAmount protected inherited
Referenced by LeapXRServiceProvider.OnPreCullHandTransforms().
TestHandPose editTimePose inherited
Referenced by LeapXRServiceProvider.Reset(), and LeapServiceProvider.Reset().
int ExtrapolationAmount protected inherited
Referenced by LeapXRServiceProvider.OnPreCullHandTransforms().
const string HAND_ARRAY_GLOBAL_NAME protected inherited
The transform array used for late-latching.
Referenced by LeapXRServiceProvider.OnPreCullHandTransforms(), and LeapXRServiceProvider.resetShaderTransforms().
long imageTimeStamp
bool manualUpdateHasBeenCalledSinceUpdate protected
const int MAX_RECONNECTION_ATTEMPTS protected inherited
The maximum number of times the provider will attempt to reconnect to the service before giving up.
const double NS_TO_S protected inherited
Converts nanoseconds to seconds.
const int RECONNECTION_INTERVAL protected inherited
The number of frames to wait between each reconnection attempt.
const double S_TO_NS protected inherited
Converts seconds to nanoseconds.
Referenced by LeapXRServiceProvider.CalculateInterpolationTime().
TransformHistory transformHistory protected
Vector3 warpedPosition protected
Quaternion warpedRotation protected
Referenced by LeapXRServiceProvider.GetWarpedMatrix().
Property Documentation
override Frame CurrentFixedFrame get inherited
override Frame CurrentFrame get inherited
Referenced by LeapXRServiceProvider.OnPreCullHandTransforms(), and LeapImageRetriever.EyeTextureData.UpdateTextures().
DeviceOffsetMode deviceOffsetMode get set
float deviceOffsetYAxis get set
Referenced by LeapXRServiceProvider.GetWarpedMatrix().
float deviceOffsetZAxis get set
Referenced by LeapXRServiceProvider.GetWarpedMatrix().
Transform deviceOrigin get set
Referenced by LeapXRServiceProvider.GetWarpedMatrix(), and LeapXRServiceProviderEditor.OnSceneGUI().
float deviceTiltXAxis get set
Referenced by LeapXRServiceProvider.GetWarpedMatrix().
Action<Device> OnDeviceSafe add remove inherited
A utility event to get a callback whenever a new device is connected to the service. This callback will ALSO trigger a callback upon subscription if a device is already connected.
For situations with multiple devices OnDeviceSafe will be dispatched once for each device.
bool updateHandInPrecull get set
Referenced by LeapXRServiceProvider.CalculateInterpolationTime(), and LeapXRServiceProvider.OnPreCullHandTransforms().
int warpingAdjustment get
Referenced by LeapXRServiceProvider.GetWarpedMatrix(), and LeapXRServiceProvider.Update().
Event Documentation
Action<Frame> OnFixedFrame inherited
Referenced by LeapProvider.DispatchFixedFrameEvent(), HandModelManager.OnDisable(), HandModelManager.OnEnable(), and InteractionHand.Start().
Action<Frame> OnUpdateFrame inherited
Referenced by LeapProvider.DispatchUpdateFrameEvent(), HandModelManager.OnDisable(), and HandModelManager.OnEnable().