Unity Modules: ExtendedFingerDetector Class Reference
ExtendedFingerDetector Class Reference
Public Member Functions
virtual void Activate ()
virtual void Deactivate ()
Public Attributes
float Period
HandModelBase HandModel
PointingState Thumb
PointingState Index
PointingState Middle
PointingState Ring
PointingState Pinky
int MinimumExtendedCount
int MaximumExtendedCount
bool ShowGizmos
UnityEvent OnActivate
UnityEvent OnDeactivate
Protected Attributes
Color OnColor
Color OffColor
Color LimitColor
Color DirectionColor
Color NormalColor
Properties
bool IsActive [get]
Detailed Description
Detects when specified fingers are in an extended or non-extended state.
You can specify whether each finger is extended, not extended, or in either state. This detector activates when every finger on the observed hand meets these conditions.
If added to a HandModelBase instance or one of its children, this detector checks the finger state at the interval specified by the Period variable. You can also specify which hand model to observe explicitly by setting handModel in the Unity editor or in code.
Since
4.1.2
Member Function Documentation
virtual void Activate () virtual inherited
Invoked when this detector activates. Subclasses must call this function when the detector's conditions become true.
Since
4.1.2
Referenced by AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
virtual void Deactivate () virtual inherited
Invoked when this detector deactivates. Subclasses must call this function when the detector's conditions change from true to false.
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
Member Data Documentation
Color DirectionColor protected inherited
Referenced by AbstractHoldDetector.changeState().
HandModelBase HandModel
The HandModelBase instance to observe. Set automatically if not explicitly set in the editor.
Since
4.1.2
PointingState Index
The required index finger state.
Color LimitColor protected inherited
int MaximumExtendedCount
The most fingers allowed to be extended for the detector to activate.
PointingState Middle
The required middle finger state.
int MinimumExtendedCount
How many fingers must be extended for the detector to activate.
Color NormalColor protected inherited
Referenced by AbstractHoldDetector.changeState().
Color OffColor protected inherited
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnActivate inherited
Dispatched when the detector activates (becomes true).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
Color OnColor protected inherited
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnDeactivate inherited
Dispatched when the detector deactivates (becomes false).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
float Period
The interval at which to check finger state.
Since
4.1.2
PointingState Pinky
The required pinky finger state.
PointingState Ring
The required ring finger state.
bool ShowGizmos
Whether to draw the detector's Gizmos for debugging. (Not every detector provides gizmos.)
Since
4.1.2
PointingState Thumb
The required thumb state.
Property Documentation
bool IsActive get inherited
The current detector state.
Since
4.1.2
Referenced by Detector.Activate(), AbstractHoldDetector.changeState(), Detector.Deactivate(), PinchDetector.ensureUpToDate(), and ProximityDetector.OnValidate().