Unity Modules: HandModelManager Class Reference
HandModelManager Class Reference
The HandModelManager manages a pool of HandModelBases and makes HandRepresentations when a it detects a Leap Hand from its configured LeapProvider.
Classes
class ModelGroup
Public Member Functions
void ReturnToPool (HandModelBase model)
HandRepresentation MakeHandRepresentation (Hand hand, ModelType modelType)
void RemoveHandRepresentation (HandRepresentation handRepresentation)
void EnableGroup (string groupName)
void DisableGroup (string groupName)
void ToggleGroup (string groupName)
void AddNewGroup (string groupName, HandModelBase leftModel, HandModelBase rightModel)
void RemoveGroup (string groupName)
T GetHandModel< T > (int handId)
Protected Member Functions
virtual void OnUpdateFrame (Frame frame)
virtual void OnFixedFrame (Frame frame)
virtual void UpdateHandRepresentations (Dictionary< int, HandRepresentation > all_hand_reps, ModelType modelType, Frame frame)
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
Dictionary< int, HandRepresentation > graphicsHandReps
Dictionary< int, HandRepresentation > physicsHandReps
bool graphicsEnabled
bool physicsEnabled
Properties
bool GraphicsEnabled [get, set]
bool PhysicsEnabled [get, set]
LeapProvider leapProvider [get, set]
Detailed Description
The HandModelManager manages a pool of HandModelBases and makes HandRepresentations when a it detects a Leap Hand from its configured LeapProvider.
When a HandRepresentation is created, a HandModelBase is removed from the pool. When a HandRepresentation is finished, its HandModelBase is returned to the pool.
This class was formerly known as HandPool.
Member Function Documentation
void AddNewGroup (string groupName, HandModelBase leftModel, HandModelBase rightModel)
Referenced by LeapHandsAutoRig.StoreStartPose().
void DisableGroup (string groupName)
DisableGroup finds and removes the ModelGroup's HandModelBases from their HandRepresentations, returns them to their ModelGroup and sets the groups IsEnabled to false.
Parameters
groupName Takes a string that matches the ModelGroup's groupName serialized in the Inspector
Referenced by HandModelManager.ToggleGroup().
void EnableGroup (string groupName)
EnableGroup finds suitable HandRepresentations and adds HandModelBases from the ModelGroup, returns them to their ModelGroup and sets the groups IsEnabled to true.
Parameters
groupName Takes a string that matches the ModelGroup's groupName serialized in the Inspector
Referenced by HandModelManager.ToggleGroup().
T GetHandModel< T > (int handId)
Type Constraints
T : HandModelBase
HandRepresentation MakeHandRepresentation (Hand hand, ModelType modelType)
MakeHandRepresentation receives a Hand and combines that with a HandModelBase to create a HandRepresentation
Parameters
hand The Leap Hand data to be drive a HandModelBase
modelType Filters for a type of hand model, for example, physics or graphics hands.
Referenced by HandModelManager.UpdateHandRepresentations().
virtual void OnDisable () protected virtual
virtual void OnEnable () protected virtual
virtual void OnFixedFrame (Frame frame) protected virtual
Updates the physics HandRepresentations.
Referenced by HandModelManager.OnDisable(), and HandModelManager.OnEnable().
virtual void OnUpdateFrame (Frame frame) protected virtual
Updates the graphics HandRepresentations.
Referenced by HandModelManager.OnDisable(), and HandModelManager.OnEnable().
void RemoveGroup (string groupName)
Referenced by LeapHandsAutoRig.PushVectorValues(), and LeapHandsAutoRig.StoreStartPose().
void RemoveHandRepresentation (HandRepresentation handRepresentation)
Referenced by HandRepresentation.Finish().
void ReturnToPool (HandModelBase model)
Referenced by HandRepresentation.Finish().
void ToggleGroup (string groupName)
virtual void UpdateHandRepresentations (Dictionary< int, HandRepresentation > all_hand_reps, ModelType modelType, Frame frame) protected virtual
Updates HandRepresentations based in the specified HandRepresentation Dictionary. Active HandRepresentation instances are updated if the hand they represent is still present in the Provider's CurrentFrame; otherwise, the HandRepresentation is removed. If new Leap Hand objects are present in the Leap HandRepresentation Dictionary, new HandRepresentations are created and added to the dictionary.
Parameters
all_hand_reps = A dictionary of Leap Hand ID's with a paired HandRepresentation
modelType Filters for a type of hand model, for example, physics or graphics hands.
frame The Leap Frame containing Leap Hand data for each currently tracked hand
Mark-and-sweep to finish unused HandRepresentations
Initialize toBeDeleted with a value to be deleted
Inform the representation that we will no longer be giving it any hand updates because the corresponding hand has gone away
Referenced by HandModelManager.OnFixedFrame(), and HandModelManager.OnUpdateFrame().
Member Data Documentation
bool graphicsEnabled protected
Dictionary<int, HandRepresentation> graphicsHandReps protected
bool physicsEnabled protected
Dictionary<int, HandRepresentation> physicsHandReps protected
Property Documentation
bool GraphicsEnabled get set
LeapProvider leapProvider get set
bool PhysicsEnabled get set