Unity Modules: RigidHand Class Reference
RigidHand Class Reference
Public Member Functions
override bool SupportsEditorPersistence ()
Returns whether or not this hand model supports editor persistence. This is false by default and must be opt-in by a developer making their own hand model script if they want editor persistence.
override void InitHand ()
override void UpdateHand ()
Vector3 GetPalmPosition ()
Quaternion GetPalmRotation ()
Vector3 GetPalmDirection ()
Vector3 GetPalmNormal ()
Vector3 GetArmDirection ()
Vector3 GetArmCenter ()
float GetArmLength ()
float GetArmWidth ()
Vector3 GetElbowPosition ()
Vector3 GetWristPosition ()
Quaternion GetArmRotation ()
override Hand GetLeapHand ()
override void SetLeapHand (Hand hand)
int LeapID ()
virtual void BeginHand ()
virtual void FinishHand ()
Public Attributes
float filtering
const int NUM_FINGERS
float handModelPalmWidth
FingerModel[] fingers
Transform palm
Transform forearm
Transform wristJoint
Transform elbowJoint
HandModelManager.ModelGroup group
Protected Member Functions
Vector3 GetPalmCenter ()
void SetPositions ()
Protected Attributes
const float PALM_CENTER_OFFSET
Hand hand_
Properties
override ModelType HandModelType [get]
override Chirality Handedness [get, set]
bool IsTracked [get]
Events
Action OnBegin
Action OnFinish
Detailed Description
A physics model for our rigid hand made out of various Unity Collider.
Member Function Documentation
virtual void BeginHand () virtual inherited
Reimplemented in CapsuleHand.
Referenced by HandRepresentation.AddModel().
virtual void FinishHand () virtual inherited
Referenced by HandRepresentation.RemoveModel().
Vector3 GetArmCenter () inherited
Calculates the center of the forearm in global coordinates.
Returns
A Vector3 containing the Unity coordinates of the center of the forearm.
Referenced by SkeletalHand.SetPositions(), and RigidHand.UpdateHand().
Vector3 GetArmDirection () inherited
Calculates the direction vector of the forearm in global coordinates.
Returns
A Vector3 representing the direction of the forearm (pointing from elbow to wrist).
float GetArmLength () inherited
Returns the measured length of the forearm in meters.
Referenced by RigidHand.UpdateHand().
Quaternion GetArmRotation () inherited
Calculates the rotation of the forearm in global coordinates.
Returns
A Quaternion representing the rotation of the arm.
Referenced by SkeletalHand.SetPositions(), RigidHand.UpdateHand(), and RiggedHand.UpdateHand().
float GetArmWidth () inherited
Returns the measured width of the forearm in meters.
Referenced by RigidHand.UpdateHand().
Vector3 GetElbowPosition () inherited
Calculates the position of the elbow in global coordinates.
Returns
A Vector3 containing the Unity coordinates of the elbow.
override Hand GetLeapHand () virtual inherited
Returns the Leap Hand object represented by this HandModel. Note that any physical quantities and directions obtained from the Leap Hand object are relative to the Leap Motion coordinate system, which uses a right-handed axes and units of millimeters.
Implements HandModelBase.
Vector3 GetPalmCenter () protected inherited
Referenced by SkeletalHand.SetPositions(), and RigidHand.UpdateHand().
Vector3 GetPalmDirection () inherited
Calculates the direction vector of the hand in global coordinates.
Returns
A Vector3 representing the direction of the hand.
Referenced by SkeletalHand.GetPalmCenter().
Vector3 GetPalmNormal () inherited
Calculates the normal vector projecting from the hand in global coordinates.
Returns
A Vector3 representing the vector perpendicular to the palm.
Vector3 GetPalmPosition () inherited
Calculates the position of the palm in global coordinates.
Returns
A Vector3 containing the Unity coordinates of the palm position.
Referenced by SkeletalHand.GetPalmCenter(), PolyHand.SetPalmOrientation(), and RiggedHand.UpdateHand().
Quaternion GetPalmRotation () inherited
Calculates the rotation of the hand in global coordinates.
Returns
A Quaternion representing the rotation of the hand.
Referenced by PolyHand.SetPalmOrientation(), SkeletalHand.SetPositions(), and RigidHand.UpdateHand().
Vector3 GetWristPosition () inherited
Calculates the position of the wrist in global coordinates.
Returns
A Vector3 containing the Unity coordinates of the wrist.
Referenced by SkeletalHand.SetPositions(), and RiggedHand.UpdateHand().
override void InitHand () virtual
Implement this function to initialise this hand after it is created. This function is called by the HandController during the Unity Update() phase when a new hand is detected by the Leap Motion device.
Reimplemented from HandModel.
int LeapID () inherited
Returns the ID associated with the hand in the Leap API. This ID is guaranteed to be unique among all hands in a frame, and is invariant for the lifetime of the hand model.
override void SetLeapHand (Hand hand) virtual inherited
Assigns a Leap Hand object to this hand model. Note that the Leap Hand objects are recreated every frame. The parent HandController calls this method to set or update the underlying hand.
Implements HandModelBase.
void SetPositions () protected inherited
Referenced by SkeletalHand.UpdateHand().
override bool SupportsEditorPersistence () virtual
Returns whether or not this hand model supports editor persistence. This is false by default and must be opt-in by a developer making their own hand model script if they want editor persistence.
Reimplemented from HandModelBase.
override void UpdateHand () virtual
Implement this function to update this hand once every game loop. For HandModel instances assigned to the HandController graphics hand list, the HandController calls this function during the Unity Update() phase. For HandModel instances in the physics hand list, the HandController calls this function in the FixedUpdate() phase.
Implements HandModel.
Member Data Documentation
Transform elbowJoint inherited
Transform object for the elbow joint of this hand.
float filtering
FingerModel [] fingers inherited
The array of finger objects for this hand. The array is ordered from thumb (element 0) to pinky (element 4).
Referenced by RiggedHand.AutoRigRiggedHand(), PolyHand.InitHand(), SkeletalHand.SetPositions(), RiggedHand.SetupRiggedHand(), LeapHandsAutoRig.StoreStartPose(), RigidHand.UpdateHand(), PolyHand.UpdateHand(), and RiggedHand.UpdateHand().
Transform forearm inherited
Transform object for the forearm object of this hand.
Referenced by SkeletalHand.SetPositions(), RigidHand.UpdateHand(), and RiggedHand.UpdateHand().
HandModelManager.ModelGroup group inherited
Referenced by HandModelManager.MakeHandRepresentation().
Hand hand_ protected inherited
The Leap Hand object this hand model represents.
Referenced by HandModel.GetLeapHand(), and RiggedHand.GetRiggedPalmRotation().
float handModelPalmWidth inherited
The model width of the hand in meters. This value is used with the measured value of the user's hand to scale the model proportionally.
const int NUM_FINGERS inherited
The number of fingers on a hand.
Transform palm inherited
Transform object for the palm object of this hand.
Referenced by RiggedHand.AutoRigRiggedHand(), RiggedHand.GetRiggedPalmRotation(), PolyHand.SetPalmOrientation(), SkeletalHand.SetPositions(), RiggedHand.SetupRiggedHand(), LeapHandsAutoRig.StoreStartPose(), RigidHand.UpdateHand(), and RiggedHand.UpdateHand().
const float PALM_CENTER_OFFSET protected inherited
Transform wristJoint inherited
Transform object for the wrist joint of this hand.
Referenced by SkeletalHand.SetPositions(), and RiggedHand.UpdateHand().
Property Documentation
override Chirality Handedness get set inherited
Referenced by RiggedHand.AutoRigRiggedHand(), and LeapHandsAutoRig.StoreStartPose().
override ModelType HandModelType get
bool IsTracked get inherited
Referenced by PinchDetector.ensureUpToDate().
Event Documentation
Action OnBegin inherited
Referenced by HandTransitionBehavior.Awake(), HandModelBase.BeginHand(), and HandTransitionBehavior.OnDestroy().
Action OnFinish inherited
Referenced by HandTransitionBehavior.Awake(), HandModelBase.FinishHand(), and HandTransitionBehavior.OnDestroy().