Unity Modules: Deque< T > Class Template Reference
Deque< T > Class Template Reference
Public Member Functions
Deque (int minCapacity=8)
void Clear ()
void PushBack (T t)
void PushFront (T t)
void PopBack ()
void PopFront ()
void PopBack (out T back)
void PopFront (out T front)
string ToDebugString ()
Properties
int Count [get]
T Front [get, set]
T Back [get, set]
T this[int index] [get, set]
Constructor & Destructor Documentation
Deque (int minCapacity = 8)
Member Function Documentation
void Clear ()
Referenced by DequeTests.Clear(), and DequeTests.Teardown().
void PopBack ()
Referenced by SlidingMax.AddValue(), and DequeTests.PushBack().
void PopBack (out T back)
void PopFront ()
Referenced by SlidingMax.AddValue(), and DequeTests.PushFront().
void PopFront (out T front)
void PushBack (T t)
Referenced by DequeTests.Clear(), DequeTests.InvalidIndex(), and DequeTests.PushFront().
void PushFront (T t)
Referenced by SlidingMax.AddValue(), DequeTests.Clear(), and DequeTests.PushBack().
string ToDebugString ()
Property Documentation
T Back get set
Referenced by SlidingMax.AddValue(), DequeTests.PushBack(), and DequeTests.PushFront().
int Count get
Referenced by SlidingMax.AddValue(), DequeTests.Clear(), DequeTests.PushBack(), and DequeTests.PushFront().
T Front get set
Referenced by DequeTests.AccessEmptyBack(), DequeTests.AccessEmptyFront(), SlidingMax.AddValue(), DequeTests.PushBack(), and DequeTests.PushFront().
T this[int index] get set