Unity Modules: RingBuffer< T > Class Template Reference
RingBuffer< T > Class Template Reference
Public Member Functions
RingBuffer (int bufferSize)
void Clear ()
void Add (T t)
T Get (int idx)
Oldest element is at index 0, youngest is at Count - 1.
T GetLatest ()
T GetOldest ()
void Set (int idx, T t)
void SetLatest (T t)
Properties
int Count [get]
int Capacity [get]
bool IsFull [get]
bool IsEmpty [get]
T this[int idx] [get, set]
Constructor & Destructor Documentation
RingBuffer (int bufferSize)
Member Function Documentation
void Add (T t)
Referenced by DeltaBuffer< Vector3, Vector3 >.Add(), and TransformHistory.UpdateDelay().
void Clear ()
Referenced by DeltaBuffer< Vector3, Vector3 >.Clear().
T Get (int idx)
Oldest element is at index 0, youngest is at Count - 1.
Referenced by DeltaBuffer< Vector3, Vector3 >.Get(), RingBuffer< Leap.Unity.TransformHistory.TransformData >.GetLatest(), DeltaBuffer< Vector3, Vector3 >.GetLatestTime(), RingBuffer< Leap.Unity.TransformHistory.TransformData >.GetOldest(), DeltaBuffer< Vector3, Vector3 >.GetTime(), and TransformHistory.TransformData.GetTransformAtTime().
T GetLatest ()
Referenced by TransformHistory.TransformData.GetTransformAtTime().
T GetOldest ()
void Set (int idx, T t)
Referenced by DeltaBuffer< Vector3, Vector3 >.Set(), and RingBuffer< Leap.Unity.TransformHistory.TransformData >.SetLatest().
void SetLatest (T t)
Property Documentation
int Capacity get
int Count get
Referenced by RingBuffer< Leap.Unity.TransformHistory.TransformData >.Get(), RingBuffer< Leap.Unity.TransformHistory.TransformData >.GetLatest(), RingBuffer< Leap.Unity.TransformHistory.TransformData >.GetOldest(), TransformHistory.TransformData.GetTransformAtTime(), RingBuffer< Leap.Unity.TransformHistory.TransformData >.Set(), and RingBuffer< Leap.Unity.TransformHistory.TransformData >.SetLatest().
bool IsEmpty get
bool IsFull get
Referenced by RingBuffer< Leap.Unity.TransformHistory.TransformData >.Add().
T this[int idx] get set