Unity Modules: DetectorLogicGate Class Reference
DetectorLogicGate Class Reference
Public Member Functions
void AddDetector (Detector detector)
void RemoveDetector (Detector detector)
void AddAllSiblingDetectors ()
virtual void Activate ()
virtual void Deactivate ()
Public Attributes
bool AddAllSiblingDetectorsOnAwake
LogicType GateType
bool Negate
UnityEvent OnActivate
UnityEvent OnDeactivate
Protected Member Functions
void CheckDetectors ()
Protected Attributes
Color OnColor
Color OffColor
Color LimitColor
Color DirectionColor
Color NormalColor
Properties
bool IsActive [get]
Detailed Description
The DetectorLogicGate detector observes other detectors and activates when these other detectors match the specified logic.
A DetectorLogicGate can be configured as an AND gate or an OR gate. You can also negate the output (creating a NAND or NOR gate).
Since a DetectorLogicGate is a Detector, it can observe other DetectorLogicGate instances. However, before constructing complex logic chains, you should consider whether it is better to put such logic into a normal script.
Since
4.1.2
Member Function Documentation
virtual void Activate () virtual inherited
Invoked when this detector activates. Subclasses must call this function when the detector's conditions become true.
Since
4.1.2
Referenced by AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
void AddAllSiblingDetectors ()
Adds all the other detectors on the same GameObject to the list of observed detectors.
Note: If you have more than one DetectorLogicGate instance on a game object, make sure that both objects don't observe each other.
Since
4.1.2
void AddDetector (Detector detector)
Adds the specified detector to the list of observed detectors.
The same detector cannot be added more than once.
Parameters
Detector the detector to watch.
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors().
void CheckDetectors () protected
Checks all the observed detectors, combines them with the specified type of logic and calls the Activate() or Deactivate() function as appropriate.
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
virtual void Deactivate () virtual inherited
Invoked when this detector deactivates. Subclasses must call this function when the detector's conditions change from true to false.
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
void RemoveDetector (Detector detector)
Removes the specified detector from the list of observed detectors;
Parameters
Detector the detector to remove.
Since
4.1.2
Member Data Documentation
bool AddAllSiblingDetectorsOnAwake
When true, all Detector components of the same game object are added to the list of watched detectors on Awake. When false, you must manually add the desired detectors.
If you have more than one DetectorLogicGate component on a game object, do not enable this option on both.
Since
4.1.2
Color DirectionColor protected inherited
Referenced by AbstractHoldDetector.changeState().
LogicType GateType
The type of logic for this gate: AND or OR.
Since
4.1.2
Color LimitColor protected inherited
bool Negate
Whether to negate the output of the gate. AND becomes NAND; OR becomes NOR.
Since
4.1.2
Color NormalColor protected inherited
Referenced by AbstractHoldDetector.changeState().
Color OffColor protected inherited
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnActivate inherited
Dispatched when the detector activates (becomes true).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
Color OnColor protected inherited
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnDeactivate inherited
Dispatched when the detector deactivates (becomes false).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
Property Documentation
bool IsActive get inherited
The current detector state.
Since
4.1.2
Referenced by Detector.Activate(), AbstractHoldDetector.changeState(), Detector.Deactivate(), PinchDetector.ensureUpToDate(), and ProximityDetector.OnValidate().