Unity Modules: Detector Class Reference
Detector Class Reference
Public Member Functions
virtual void Activate ()
virtual void Deactivate ()
Public Attributes
UnityEvent OnActivate
UnityEvent OnDeactivate
Protected Attributes
Color OnColor
Color OffColor
Color LimitColor
Color DirectionColor
Color NormalColor
Properties
bool IsActive [get]
Detailed Description
Base class for detectors.
A Detector is an object that observes some aspect of a scene and reports true when the specified conditions are met. Typically these conditions involve hand information, but this is not required.
Detector implementations must call Activate() when their conditions are met and Deactivate() when those conditions are no longer met. Implementations should also call Deactivate() when they, or the object they are a component of become disabled. Implementations can call Activate() and Deactivate() more often than is strictly necessary. This Detector base class keeps track of the IsActive status and only dispatches events when the status changes.
Since
4.1.2
Member Function Documentation
virtual void Activate () virtual
Invoked when this detector activates. Subclasses must call this function when the detector's conditions become true.
Since
4.1.2
Referenced by AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
virtual void Deactivate () virtual
Invoked when this detector deactivates. Subclasses must call this function when the detector's conditions change from true to false.
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), AbstractHoldDetector.changeState(), DetectorLogicGate.CheckDetectors(), and ProximityDetector.OnValidate().
Member Data Documentation
Color DirectionColor protected
Referenced by AbstractHoldDetector.changeState().
Color LimitColor protected
Color NormalColor protected
Referenced by AbstractHoldDetector.changeState().
Color OffColor protected
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnActivate
Dispatched when the detector activates (becomes true).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
Color OnColor protected
Referenced by AbstractHoldDetector.changeState().
UnityEvent OnDeactivate
Dispatched when the detector deactivates (becomes false).
Since
4.1.2
Referenced by DetectorLogicGate.AddAllSiblingDetectors(), and DetectorLogicGate.RemoveDetector().
Property Documentation
bool IsActive get
The current detector state.
Since
4.1.2
Referenced by Detector.Activate(), AbstractHoldDetector.changeState(), Detector.Deactivate(), PinchDetector.ensureUpToDate(), and ProximityDetector.OnValidate().