Unity Modules: DeltaBuffer< SampleType, DerivativeType > Class Template Reference
DeltaBuffer< SampleType, DerivativeType > Class Template Reference abstract
Allows you to add to a capped-size ring buffer of Ts and, when full, compute the buffer's average change over time. DeltaBuffer without type parameters supports Vector3s; DeltaFloatBuffer supports floats, and DeltaQuaternionBuffer supports Quaternion rotations.
Classes
struct ValueTimePair
Public Member Functions
DeltaBuffer (int bufferSize)
void Clear ()
void Add (SampleType sample, float sampleTime)
SampleType Get (int idx)
SampleType GetLatest ()
void Set (int idx, SampleType sample, float sampleTime)
void SetLatest (SampleType sample, float sampleTime)
float GetTime (int idx)
float GetLatestTime ()
abstract DerivativeType Delta ()
Returns the average change between each sample per unit time.
IndexableEnumerator< SampleType > GetEnumerator ()
DeltaBuffer (int bufferSize)
override Vector3 Delta ()
Returns the average change between each sample per unit time, or zero if the buffer contains one or fewer elements.
Protected Attributes
RingBuffer< ValueTimePair > _buffer
Properties
int Count [get]
bool IsFull [get]
bool IsEmpty [get]
int Capacity [get]
SampleType this[int idx] [get]
Detailed Description
Allows you to add to a capped-size ring buffer of Ts and, when full, compute the buffer's average change over time. DeltaBuffer without type parameters supports Vector3s; DeltaFloatBuffer supports floats, and DeltaQuaternionBuffer supports Quaternion rotations.
A ring buffer of Vector3s with a Delta() function that computes the buffer's average change over time.
To support other types, subclass DeltaBuffer with your sample type and average change type (in many cases the these are the same) and implement the Delta() function to compute the average change of samples currently in the buffer.
The larger the buffer, the more stable but also delayed the resulting average change over time. A buffer size of 5 is a good start for 60-90 Hz updates.
Constructor & Destructor Documentation
DeltaBuffer (int bufferSize)
DeltaBuffer (int bufferSize)
Member Function Documentation
void Add (SampleType sample, float sampleTime)
void Clear ()
abstract DerivativeType Delta () pure virtual
Returns the average change between each sample per unit time.
If the buffer is empty, you should return the identity for your derivative type.
Implements DeltaBuffer< Vector3, Vector3 >.
Implemented in DeltaQuaternionBuffer, DeltaFloatBuffer, DeltaBuffer< SampleType, DerivativeType >, DeltaBuffer< float, float >, DeltaBuffer< Quaternion, Vector3 >, DeltaBuffer< SampleType, DerivativeType >, DeltaBuffer< float, float >, and DeltaBuffer< Quaternion, Vector3 >.
Referenced by DeltaBuffer< Vector3, Vector3 >.GetLatestTime().
override Vector3 Delta () virtual
Returns the average change between each sample per unit time, or zero if the buffer contains one or fewer elements.
The larger the buffer, the more stable but also delayed the resulting average change over time. A buffer size of 5 is a good start for 60-90 Hz updates.
Implements DeltaBuffer< Vector3, Vector3 >.
SampleType Get (int idx)
Referenced by DeltaBuffer< Vector3, Vector3 >.Delta(), DeltaFloatBuffer.Delta(), and DeltaBuffer< Vector3, Vector3 >.GetLatest().
IndexableEnumerator<SampleType> GetEnumerator ()
SampleType GetLatest ()
float GetLatestTime ()
Referenced by DeltaBuffer< Vector3, Vector3 >.Add().
float GetTime (int idx)
Referenced by DeltaBuffer< Vector3, Vector3 >.Delta(), and DeltaFloatBuffer.Delta().
void Set (int idx, SampleType sample, float sampleTime)
Referenced by DeltaBuffer< Vector3, Vector3 >.SetLatest().
void SetLatest (SampleType sample, float sampleTime)
Referenced by DeltaBuffer< Vector3, Vector3 >.Add().
Member Data Documentation
RingBuffer<ValueTimePair> _buffer protected
Referenced by DeltaQuaternionBuffer.Delta(), and DeltaBuffer< Vector3, Vector3 >.DeltaBuffer().
Property Documentation
int Capacity get
int Count get
Referenced by DeltaBuffer< Vector3, Vector3 >.Delta(), DeltaFloatBuffer.Delta(), DeltaQuaternionBuffer.Delta(), DeltaBuffer< Vector3, Vector3 >.GetLatest(), DeltaBuffer< Vector3, Vector3 >.GetLatestTime(), and DeltaBuffer< Vector3, Vector3 >.SetLatest().
bool IsEmpty get
Referenced by DeltaBuffer< Vector3, Vector3 >.Add().
bool IsFull get
SampleType this[int idx] get