Unity Modules: AssetFolderPropertyDrawer Class Reference
AssetFolderPropertyDrawer Class Reference
Public Member Functions
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
Protected Member Functions
virtual string PromptUserForPath (string currentPath)
virtual bool ValidateObject (Object asset, out string errorMessage)
virtual bool ValidatePath (string fullPath, string relativePath, out string errorMessage)
Member Function Documentation
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
virtual string PromptUserForPath (string currentPath) protected virtual
Reimplemented in StreamingAssetPropertyDrawer.
Referenced by AssetFolderPropertyDrawer.OnGUI().
virtual bool ValidateObject (Object asset, out string errorMessage) protected virtual
Referenced by AssetFolderPropertyDrawer.OnGUI().
virtual bool ValidatePath (string fullPath, string relativePath, out string errorMessage) protected virtual
Reimplemented in StreamingAssetPropertyDrawer, and StreamingFolderPropertyDrawer.
Referenced by AssetFolderPropertyDrawer.OnGUI(), and AssetFolderPropertyDrawer.ValidateObject().