Unity Modules: LeapSphericalSpace Class Reference
LeapSphericalSpace Class Reference
Classes
class Transformer
Public Member Functions
override Hash GetSettingHash ()
Get a hash of all features in this space. This is useful if you want to know if anything has changed about the settings of this space.
void RebuildHierarchy ()
Call to traverse the entire hierarchy and rebuild the relationship between anchors. Call this whenever any of the following happens:
void RecalculateTransformers ()
Call to update all transformers in the space. Call this whenever any anchor or parent of an anchor changes it's transform.
void RecalculateParentAnchor ()
Static Public Member Functions
static LeapSpaceAnchor GetAnchor (Transform root)
Public Attributes
LeapSpaceAnchor parent
LeapSpace space
ITransformer transformer
Protected Member Functions
override ITransformer CosntructBaseTransformer ()
override ITransformer ConstructTransformer (LeapSpaceAnchor anchor)
override void UpdateRadialTransformer (ITransformer transformer, ITransformer parent, Vector3 rectSpaceDelta)
sealed override void UpdateTransformer (ITransformer transformer, ITransformer parent)
override void OnEnable ()
override void OnDisable ()
Properties
float radius [get, set]
static List< LeapSpace > allEnabled [get]
List< LeapSpaceAnchor > anchors [get]
Returns all active anchors in depth-first pre-order
Member Function Documentation
override ITransformer ConstructTransformer (LeapSpaceAnchor anchor) protected virtual
Implements LeapSpace.
override ITransformer CosntructBaseTransformer () protected virtual
Implements LeapSpace.
static LeapSpaceAnchor GetAnchor (Transform root) static inherited
Referenced by LeapGraphicGroup.OnDisable(), LeapGraphicGroup.RefreshGraphicAnchors(), and LeapGraphicGroup.TryAddGraphic().
override Hash GetSettingHash () virtual inherited
Get a hash of all features in this space. This is useful if you want to know if anything has changed about the settings of this space.
Implements LeapSpace.
override void OnDisable () protected virtual inherited
Reimplemented from LeapSpaceAnchor.
override void OnEnable () protected virtual inherited
Reimplemented from LeapSpaceAnchor.
void RebuildHierarchy () inherited
Call to traverse the entire hierarchy and rebuild the relationship between anchors. Call this whenever any of the following happens:
An anchor is created
An anchor is enabled / disabled
An enabled anchor is destroyed
The relative position in the hierarchy of any two anchors changes.
Referenced by LeapGraphicGroup.OnDisable(), LeapGraphicRenderer.TryAddGraphic(), and LeapGraphicRenderer.validateSpaceComponent().
void RecalculateParentAnchor () inherited
Referenced by LeapSpace.RecalculateTransformers().
void RecalculateTransformers () inherited
Call to update all transformers in the space. Call this whenever any anchor or parent of an anchor changes it's transform.
Referenced by LeapGraphicRenderer.TryAddGraphic(), and LeapGraphicRenderer.validateSpaceComponent().
override void UpdateRadialTransformer (ITransformer transformer, ITransformer parent, Vector3 rectSpaceDelta) protected virtual
Implements LeapRadialSpace.
sealed override void UpdateTransformer (ITransformer transformer, ITransformer parent) protected virtual inherited
Implements LeapSpace.
Member Data Documentation
LeapSpaceAnchor parent inherited
Referenced by LeapSpaceAnchor.GetAnchor().
LeapSpace space inherited
Referenced by IdentityTransformer.GetTransformationMatrix(), LeapGraphicGroup.OnDisable(), LeapSpace.RecalculateTransformers(), InteractionController.TransformPoint(), and LeapGraphicGroup.TryAddGraphic().
ITransformer transformer inherited
Referenced by InteractionController.TransformPoint(), InteractionHand.unwarpColliders(), InteractionXRController.unwarpColliders(), and ActivityManager< Leap.Unity.Interaction.IInteractionBehaviour >.UpdateActivityQuery().
Property Documentation
List<LeapSpace> allEnabled static get inherited
Referenced by InteractionController.SwapGrasp().
List<LeapSpaceAnchor> anchors get inherited
Returns all active anchors in depth-first pre-order
float radius get set inherited