Unity Modules: RendererMeshData Class Reference
RendererMeshData Class Reference
Public Member Functions
void Clear ()
Mesh GetMeshFromPoolOrNew ()
void ClearPool ()
void AddMesh (Mesh mesh)
void RemoveMesh (int index)
void Validate (LeapRenderingMethod renderingMethod)
Properties
int Count [get]
Mesh this[int index] [get, set]
Member Function Documentation
void AddMesh (Mesh mesh)
Referenced by LeapTextRenderer.OnAddRemoveGraphics(), and LeapTextRenderer.OnUpdateRenderer().
void Clear ()
void ClearPool ()
Mesh GetMeshFromPoolOrNew ()
void RemoveMesh (int index)
Referenced by LeapTextRenderer.OnAddRemoveGraphics(), and LeapTextRenderer.OnUpdateRenderer().
void Validate (LeapRenderingMethod renderingMethod)
Referenced by LeapTextRenderer.OnUpdateRenderer().
Property Documentation
int Count get
Referenced by LeapTextRenderer.OnAddRemoveGraphics(), and LeapTextRenderer.OnUpdateRenderer().
Mesh this[int index] get set