Unity Modules: LeapC Class Reference
LeapC Class Reference
Classes
struct LEAP_RECORDING_PARAMETERS
struct LEAP_RECORDING_STATUS
Public Member Functions
static long GetNow ()
static eLeapRS CreateClockRebaser (out IntPtr phClockRebaser)
static eLeapRS DestroyClockRebaser (IntPtr hClockRebaser)
static eLeapRS UpdateRebase (IntPtr hClockRebaser, Int64 userClock, Int64 leapClock)
static eLeapRS RebaseClock (IntPtr hClockRebaser, Int64 userClock, out Int64 leapClock)
static eLeapRS CreateConnection (ref LEAP_CONNECTION_CONFIG pConfig, out IntPtr pConnection)
static eLeapRS GetConnectionInfo (IntPtr hConnection, ref LEAP_CONNECTION_INFO pInfo)
static eLeapRS OpenConnection (IntPtr hConnection)
static eLeapRS SetAllocator (IntPtr hConnection, ref LEAP_ALLOCATOR pAllocator)
static eLeapRS GetDeviceList (IntPtr hConnection, [In, Out] LEAP_DEVICE_REF[] pArray, out UInt32 pnArray)
static eLeapRS OpenDevice (LEAP_DEVICE_REF rDevice, out IntPtr pDevice)
static eLeapRS GetDeviceInfo (IntPtr hDevice, ref LEAP_DEVICE_INFO info)
static eLeapRS SetPolicyFlags (IntPtr hConnection, UInt64 set, UInt64 clear)
static eLeapRS SetDeviceFlags (IntPtr hDevice, UInt64 set, UInt64 clear, out UInt64 prior)
static eLeapRS PollConnection (IntPtr hConnection, UInt32 timeout, ref LEAP_CONNECTION_MESSAGE msg)
static eLeapRS GetFrameSize (IntPtr hConnection, Int64 timestamp, out UInt64 pncbEvent)
static eLeapRS InterpolateFrame (IntPtr hConnection, Int64 timestamp, IntPtr pEvent, UInt64 ncbEvent)
static eLeapRS InterpolateFrameFromTime (IntPtr hConnection, Int64 timestamp, Int64 sourceTimestamp, IntPtr pEvent, UInt64 ncbEvent)
static eLeapRS InterpolateHeadPose (IntPtr hConnection, Int64 timestamp, ref LEAP_HEAD_POSE_EVENT headPose)
static LEAP_VECTOR LeapPixelToRectilinear (IntPtr hConnection, eLeapPerspectiveType camera, LEAP_VECTOR pixel)
static LEAP_VECTOR LeapRectilinearToPixel (IntPtr hConnection, eLeapPerspectiveType camera, LEAP_VECTOR rectilinear)
static void CloseDevice (IntPtr pDevice)
static eLeapRS CloseConnection (IntPtr hConnection)
static void DestroyConnection (IntPtr connection)
static eLeapRS RequestConfigValue (IntPtr hConnection, string name, out UInt32 request_id)
static eLeapRS GetPointMappingSize (IntPtr hConnection, ref ulong pSize)
static eLeapRS GetPointMapping (IntPtr hConnection, IntPtr pointMapping, ref ulong pSize)
static eLeapRS RecordingOpen (ref IntPtr ppRecording, string userPath, LEAP_RECORDING_PARAMETERS parameters)
static eLeapRS RecordingClose (ref IntPtr ppRecording)
static eLeapRS LeapRecordingGetStatus (IntPtr pRecording, ref LEAP_RECORDING_STATUS status)
static eLeapRS RecordingReadSize (IntPtr pRecording, ref UInt64 pncbEvent)
static eLeapRS RecordingRead (IntPtr pRecording, ref LEAP_TRACKING_EVENT pEvent, UInt64 ncbEvent)
static eLeapRS RecordingWrite (IntPtr pRecording, ref LEAP_TRACKING_EVENT pEvent, ref UInt64 pnBytesWritten)
static eLeapRS LeapTelemetryProfiling (IntPtr hConnection, ref LEAP_TELEMETRY_DATA telemetryData)
static UInt64 TelemetryGetNow ()
Static Public Member Functions
static eLeapRS CreateConnection (out IntPtr pConnection)
static eLeapRS GetDeviceCount (IntPtr hConnection, out UInt32 deviceCount)
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, bool value, out UInt32 requestId)
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, Int32 value, out UInt32 requestId)
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, float value, out UInt32 requestId)
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, string value, out UInt32 requestId)
Static Public Attributes
static int DistortionSize
Member Function Documentation
static eLeapRS CloseConnection (IntPtr hConnection)
Referenced by Connection.Stop().
static void CloseDevice (IntPtr pDevice)
Referenced by LeapCTests.TestCloseDevice().
static eLeapRS CreateClockRebaser (out IntPtr phClockRebaser)
Referenced by LeapCTests.TestRebaserLifeCycle().
static eLeapRS CreateConnection (ref LEAP_CONNECTION_CONFIG pConfig, out IntPtr pConnection)
Referenced by Connection.Start(), LeapCTests.TestBoolConfigReadWrite(), LeapCTests.TestCloseDevice(), LeapCTests.TestCreateConnection(), LeapCStressTests.TestCreateDestroy(), LeapCStressTests.TestCreateDestroyWithConfigRequest(), LeapCTests.TestDestroyConnection(), LeapCTests.TestFloatConfigReadWrite(), LeapCTests.TestGetConnectionInfo(), LeapCTests.TestGetDeviceInfo(), LeapCTests.TestGetDeviceList(), LeapCTests.TestGetOneDeviceInfo(), LeapCTests.TestGetStringConfigValue(), LeapCTests.TestInt32ConfigReadWrite(), LeapCTests.TestInterpolateFrames(), LeapCTests.TestOpenConnection(), LeapCTests.TestOpenDevice(), LeapCTests.TestPollConnection(), LeapCTests.TestReadFloatConfig(), LeapCTests.TestSetDeviceFlags(), LeapCTests.TestSetPolicyFlags(), and LeapCTests.TestStringConfigReadWrite().
static eLeapRS CreateConnection (out IntPtr pConnection) static
static eLeapRS DestroyClockRebaser (IntPtr hClockRebaser)
Referenced by LeapCTests.TestRebaserLifeCycle().
static void DestroyConnection (IntPtr connection)
Referenced by Connection.Dispose(), LeapCStressTests.TestCreateDestroy(), LeapCStressTests.TestCreateDestroyWithConfigRequest(), and LeapCTests.TestDestroyConnection().
static eLeapRS GetConnectionInfo (IntPtr hConnection, ref LEAP_CONNECTION_INFO pInfo)
Referenced by LeapCTests.TestGetConnectionInfo(), and LeapCTests.TestOpenConnection().
static eLeapRS GetDeviceCount (IntPtr hConnection, out UInt32 deviceCount) static
Referenced by LeapCTests.TestCloseDevice(), LeapCTests.TestGetDeviceInfo(), LeapCTests.TestGetDeviceList(), LeapCTests.TestOpenDevice(), and LeapCTests.TestSetDeviceFlags().
static eLeapRS GetDeviceInfo (IntPtr hDevice, ref LEAP_DEVICE_INFO info)
Referenced by Connection.GetInterpolatedLeftRightTransform(), LeapCTests.TestGetDeviceInfo(), and LeapCTests.TestGetOneDeviceInfo().
static eLeapRS GetDeviceList (IntPtr hConnection, [In, Out] LEAP_DEVICE_REF[] pArray, out UInt32 pnArray)
Referenced by LeapCTests.TestCloseDevice(), LeapCTests.TestGetDeviceInfo(), LeapCTests.TestGetDeviceList(), LeapCTests.TestOpenDevice(), and LeapCTests.TestSetDeviceFlags().
static eLeapRS GetFrameSize (IntPtr hConnection, Int64 timestamp, out UInt64 pncbEvent)
Referenced by Connection.GetInterpolatedFrameSize(), and LeapCTests.TestInterpolateFrames().
static long GetNow ()
Referenced by Connection.GetPointMapping(), Controller.Now(), LeapCTests.TestNow(), and LeapCTests.TestRebaserLifeCycle().
static eLeapRS GetPointMapping (IntPtr hConnection, IntPtr pointMapping, ref ulong pSize)
Referenced by Connection.GetPointMapping().
static eLeapRS GetPointMappingSize (IntPtr hConnection, ref ulong pSize)
static eLeapRS InterpolateFrame (IntPtr hConnection, Int64 timestamp, IntPtr pEvent, UInt64 ncbEvent)
Referenced by Connection.GetInterpolatedFrame(), and LeapCTests.TestInterpolateFrames().
static eLeapRS InterpolateFrameFromTime (IntPtr hConnection, Int64 timestamp, Int64 sourceTimestamp, IntPtr pEvent, UInt64 ncbEvent)
Referenced by Connection.GetInterpolatedFrameFromTime(), and Connection.GetInterpolatedLeftRightTransform().
static eLeapRS InterpolateHeadPose (IntPtr hConnection, Int64 timestamp, ref LEAP_HEAD_POSE_EVENT headPose)
Referenced by Connection.GetInterpolatedHeadPose().
static LEAP_VECTOR LeapPixelToRectilinear (IntPtr hConnection, eLeapPerspectiveType camera, LEAP_VECTOR pixel)
Referenced by Connection.PixelToRectilinear().
static eLeapRS LeapRecordingGetStatus (IntPtr pRecording, ref LEAP_RECORDING_STATUS status)
static LEAP_VECTOR LeapRectilinearToPixel (IntPtr hConnection, eLeapPerspectiveType camera, LEAP_VECTOR rectilinear)
Referenced by Connection.RectilinearToPixel().
static eLeapRS LeapTelemetryProfiling (IntPtr hConnection, ref LEAP_TELEMETRY_DATA telemetryData)
Referenced by Connection.TelemetryProfiling().
static eLeapRS OpenConnection (IntPtr hConnection)
Referenced by Connection.Start(), LeapCTests.TestBoolConfigReadWrite(), LeapCTests.TestCloseDevice(), LeapCStressTests.TestCreateDestroy(), LeapCStressTests.TestCreateDestroyWithConfigRequest(), LeapCTests.TestFloatConfigReadWrite(), LeapCTests.TestGetConnectionInfo(), LeapCTests.TestGetDeviceInfo(), LeapCTests.TestGetDeviceList(), LeapCTests.TestGetOneDeviceInfo(), LeapCTests.TestGetStringConfigValue(), LeapCTests.TestInt32ConfigReadWrite(), LeapCTests.TestInterpolateFrames(), LeapCTests.TestOpenConnection(), LeapCTests.TestOpenDevice(), LeapCTests.TestPollConnection(), LeapCTests.TestReadFloatConfig(), LeapCTests.TestSetDeviceFlags(), LeapCTests.TestSetPolicyFlags(), and LeapCTests.TestStringConfigReadWrite().
static eLeapRS OpenDevice (LEAP_DEVICE_REF rDevice, out IntPtr pDevice)
Referenced by Connection.GetInterpolatedLeftRightTransform(), LeapCTests.TestCloseDevice(), LeapCTests.TestGetDeviceInfo(), LeapCTests.TestGetOneDeviceInfo(), LeapCTests.TestOpenDevice(), and LeapCTests.TestSetDeviceFlags().
static eLeapRS PollConnection (IntPtr hConnection, UInt32 timeout, ref LEAP_CONNECTION_MESSAGE msg)
Referenced by Connection.Stop(), LeapCTests.TestBoolConfigReadWrite(), LeapCTests.TestCloseDevice(), LeapCTests.TestFloatConfigReadWrite(), LeapCTests.TestGetConnectionInfo(), LeapCTests.TestGetDeviceInfo(), LeapCTests.TestGetDeviceList(), LeapCTests.TestGetOneDeviceInfo(), LeapCTests.TestGetStringConfigValue(), LeapCTests.TestInt32ConfigReadWrite(), LeapCTests.TestInterpolateFrames(), LeapCTests.TestOpenDevice(), LeapCTests.TestPollConnection(), LeapCTests.TestReadFloatConfig(), LeapCTests.TestSetDeviceFlags(), LeapCTests.TestSetPolicyFlags(), and LeapCTests.TestStringConfigReadWrite().
static eLeapRS RebaseClock (IntPtr hClockRebaser, Int64 userClock, out Int64 leapClock)
Referenced by LeapCTests.TestRebaserLifeCycle().
static eLeapRS RecordingClose (ref IntPtr ppRecording)
static eLeapRS RecordingOpen (ref IntPtr ppRecording, string userPath, LEAP_RECORDING_PARAMETERS parameters)
static eLeapRS RecordingRead (IntPtr pRecording, ref LEAP_TRACKING_EVENT pEvent, UInt64 ncbEvent)
static eLeapRS RecordingReadSize (IntPtr pRecording, ref UInt64 pncbEvent)
static eLeapRS RecordingWrite (IntPtr pRecording, ref LEAP_TRACKING_EVENT pEvent, ref UInt64 pnBytesWritten)
static eLeapRS RequestConfigValue (IntPtr hConnection, string name, out UInt32 request_id)
Referenced by Connection.GetConfigValue(), LeapCTests.TestBoolConfigReadWrite(), LeapCStressTests.TestCreateDestroyWithConfigRequest(), LeapCTests.TestFloatConfigReadWrite(), LeapCTests.TestGetStringConfigValue(), LeapCTests.TestInt32ConfigReadWrite(), LeapCTests.TestReadFloatConfig(), and LeapCTests.TestStringConfigReadWrite().
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, bool value, out UInt32 requestId) static
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, Int32 value, out UInt32 requestId) static
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, float value, out UInt32 requestId) static
static eLeapRS SaveConfigValue (IntPtr hConnection, string key, string value, out UInt32 requestId) static
static eLeapRS SetAllocator (IntPtr hConnection, ref LEAP_ALLOCATOR pAllocator)
Referenced by Connection.Start().
static eLeapRS SetDeviceFlags (IntPtr hDevice, UInt64 set, UInt64 clear, out UInt64 prior)
Referenced by Device.SetPaused(), and LeapCTests.TestSetDeviceFlags().
static eLeapRS SetPolicyFlags (IntPtr hConnection, UInt64 set, UInt64 clear)
Referenced by Connection.ClearPolicy(), Connection.SetPolicy(), and LeapCTests.TestSetPolicyFlags().
static UInt64 TelemetryGetNow ()
Referenced by Controller.TelemetryGetNow().
static eLeapRS UpdateRebase (IntPtr hClockRebaser, Int64 userClock, Int64 leapClock)
Referenced by LeapCTests.TestRebaserLifeCycle().
Member Data Documentation
int DistortionSize static
Referenced by Connection.GetInterpolatedLeftRightTransform().