Unity Modules: IInternalInteractionController Interface Reference
IInternalInteractionController Interface Reference
Public Member Functions
void FixedUpdateController ()
bool CheckHoverEnd (out HashSet< IInteractionBehaviour > hoverEndedObjects)
bool CheckHoverBegin (out HashSet< IInteractionBehaviour > hoverBeganObjects)
bool CheckHoverStay (out HashSet< IInteractionBehaviour > hoveredObjects)
bool CheckPrimaryHoverEnd (out IInteractionBehaviour primaryHoverEndedObject)
bool CheckPrimaryHoverBegin (out IInteractionBehaviour primaryHoverBeganObject)
bool CheckPrimaryHoverStay (out IInteractionBehaviour primaryHoveredObject)
bool CheckContactEnd (out HashSet< IInteractionBehaviour > contactEndedObjects)
bool CheckContactBegin (out HashSet< IInteractionBehaviour > contactBeganObjects)
bool CheckContactStay (out HashSet< IInteractionBehaviour > contactedObjects)
bool CheckGraspEnd (out IInteractionBehaviour releasedObject)
bool CheckGraspBegin (out IInteractionBehaviour newlyGraspedObject)
bool CheckGraspHold (out IInteractionBehaviour graspedObject)
bool CheckSuspensionBegin (out IInteractionBehaviour suspendedObject)
bool CheckSuspensionEnd (out IInteractionBehaviour resumedObject)
Member Function Documentation
bool CheckContactBegin (out HashSet< IInteractionBehaviour > contactBeganObjects)
Referenced by InteractionController.ClearContactTrackingForObject().
bool CheckContactEnd (out HashSet< IInteractionBehaviour > contactEndedObjects)
Referenced by InteractionController.ClearContactTrackingForObject().
bool CheckContactStay (out HashSet< IInteractionBehaviour > contactedObjects)
Referenced by InteractionController.ClearContactTrackingForObject().
bool CheckGraspBegin (out IInteractionBehaviour newlyGraspedObject)
Referenced by InteractionController.ReleaseObject().
bool CheckGraspEnd (out IInteractionBehaviour releasedObject)
Referenced by InteractionController.ReleaseObject().
bool CheckGraspHold (out IInteractionBehaviour graspedObject)
Referenced by InteractionController.ReleaseObject().
bool CheckHoverBegin (out HashSet< IInteractionBehaviour > hoverBeganObjects)
Referenced by InteractionController.ClearHoverTrackingForObject().
bool CheckHoverEnd (out HashSet< IInteractionBehaviour > hoverEndedObjects)
Referenced by InteractionController.ClearHoverTrackingForObject().
bool CheckHoverStay (out HashSet< IInteractionBehaviour > hoveredObjects)
Referenced by InteractionController.ClearHoverTrackingForObject().
bool CheckPrimaryHoverBegin (out IInteractionBehaviour primaryHoverBeganObject)
Referenced by InteractionController.ClearPrimaryHoverTracking().
bool CheckPrimaryHoverEnd (out IInteractionBehaviour primaryHoverEndedObject)
Referenced by InteractionController.ClearPrimaryHoverTracking().
bool CheckPrimaryHoverStay (out IInteractionBehaviour primaryHoveredObject)
Referenced by InteractionController.ClearPrimaryHoverTracking().
bool CheckSuspensionBegin (out IInteractionBehaviour suspendedObject)
Referenced by InteractionController.ReleaseObject().
bool CheckSuspensionEnd (out IInteractionBehaviour resumedObject)
Referenced by InteractionController.ReleaseObject().
void FixedUpdateController ()
Referenced by InteractionController.OnDisable().