Unity Modules: IInteractionBehaviour Interface Reference
IInteractionBehaviour Interface Reference
IInteractionBehaviour is the interface that defines all Interaction objects, specifying the minimum set of functionality required to make objects interactable.
Public Member Functions
void FixedUpdateObject ()
float GetHoverDistance (Vector3 worldPosition)
void BeginHover (List< InteractionController > beganHovering)
void EndHover (List< InteractionController > endedHovering)
void StayHovered (List< InteractionController > currentlyHovering)
void BeginPrimaryHover (List< InteractionController > beganPrimaryHovering)
void EndPrimaryHover (List< InteractionController > endedPrimaryHovering)
void StayPrimaryHovered (List< InteractionController > currentlyPrimaryHovering)
void BeginContact (List< InteractionController > beganContact)
void EndContact (List< InteractionController > endedContact)
void StayContacted (List< InteractionController > currentlyContacting)
void BeginGrasp (List< InteractionController > beganGrasping)
void EndGrasp (List< InteractionController > endedGrasping)
void StayGrasped (List< InteractionController > currentlyGrasping)
void BeginSuspension (InteractionController beganSuspending)
void EndSuspension (InteractionController endedSuspending)
Properties
string name [get]
GameObject gameObject [get]
Transform transform [get]
InteractionManager manager [get]
Rigidbody rigidbody [get]
ISpaceComponent space [get]
IgnoreHoverMode ignoreHoverMode [get]
bool ignorePrimaryHover [get]
bool ignoreContact [get]
bool ignoreGrasping [get]
bool allowMultiGrasp [get]
SingleLayer interactionLayer [get]
SingleLayer noContactLayer [get]
bool isGrasped [get]
bool isSuspended [get]
Detailed Description
IInteractionBehaviour is the interface that defines all Interaction objects, specifying the minimum set of functionality required to make objects interactable.
Member Function Documentation
void BeginContact (List< InteractionController > beganContact)
Implemented in InteractionBehaviour.
void BeginGrasp (List< InteractionController > beganGrasping)
Implemented in InteractionBehaviour.
Referenced by InteractionHand.checkShouldGraspAtemporal(), InteractionXRController.checkShouldGraspAtemporal(), and InteractionController.SwapGrasp().
void BeginHover (List< InteractionController > beganHovering)
Implemented in InteractionBehaviour.
void BeginPrimaryHover (List< InteractionController > beganPrimaryHovering)
Implemented in InteractionBehaviour.
void BeginSuspension (InteractionController beganSuspending)
Implemented in InteractionBehaviour.
void EndContact (List< InteractionController > endedContact)
Implemented in InteractionBehaviour.
Referenced by InteractionController.ClearContactTrackingForObject().
void EndGrasp (List< InteractionController > endedGrasping)
Implemented in InteractionBehaviour.
Referenced by InteractionController.ReleaseGrasps().
void EndHover (List< InteractionController > endedHovering)
Implemented in InteractionBehaviour.
Referenced by InteractionController.ClearHoverTrackingForObject().
void EndPrimaryHover (List< InteractionController > endedPrimaryHovering)
Implemented in InteractionBehaviour.
Referenced by InteractionController.ClearPrimaryHoverTracking().
void EndSuspension (InteractionController endedSuspending)
Implemented in InteractionBehaviour.
void FixedUpdateObject ()
Implemented in InteractionBehaviour.
float GetHoverDistance (Vector3 worldPosition)
Implemented in InteractionBehaviour.
Referenced by InteractionXRController.checkShouldGraspAtemporal(), InteractionXRController.fixedUpdateGraspingState(), and InteractionController.GetHoverDistance().
void StayContacted (List< InteractionController > currentlyContacting)
Implemented in InteractionBehaviour.
void StayGrasped (List< InteractionController > currentlyGrasping)
Implemented in InteractionBehaviour.
void StayHovered (List< InteractionController > currentlyHovering)
Implemented in InteractionBehaviour.
void StayPrimaryHovered (List< InteractionController > currentlyPrimaryHovering)
Implemented in InteractionBehaviour.
Property Documentation
bool allowMultiGrasp get
Referenced by InteractionController.SwapGrasp().
GameObject gameObject get
Referenced by HeuristicGrabClassifier.FixedUpdateClassifierRelease(), and InteractionButtonEditor.OnInspectorGUI().
bool ignoreContact get
Referenced by InteractionController.NotifyContactBoneCollisionExit().
bool ignoreGrasping get
Referenced by InteractionController.ReleaseObject().
IgnoreHoverMode ignoreHoverMode get
bool ignorePrimaryHover get
SingleLayer interactionLayer get
bool isGrasped get
Referenced by HeuristicGrabClassifier.FillClassifier(), and InteractionController.SwapGrasp().
bool isSuspended get
Referenced by InteractionController.ReleaseObject().
InteractionManager manager get
string name get
Referenced by InteractionController.ReleaseGrasps().
SingleLayer noContactLayer get
Rigidbody rigidbody get
Referenced by InteractionXRController.OnDrawRuntimeGizmos(), InteractionManager.RegisterInteractionBehaviour(), HeuristicGrabClassifier.SwapClassifierState(), and InteractionManager.UnregisterInteractionBehaviour().
ISpaceComponent space get
Referenced by InteractionController.GetHoverDistance().
Transform transform get
Referenced by WorkstationBehaviourExample.DeactivateWorkstation(), InteractionButtonEditor.OnInspectorGUI(), and HeuristicGrabClassifier.SwapClassifierState().