Unity Modules: IInternalInteractionManager Interface Reference
IInternalInteractionManager Interface Reference
Public Member Functions
void NotifyIntObjAddedInteractionLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately=true)
void NotifyIntObjRemovedInteractionLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately=true)
void NotifyIntObjAddedNoContactLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately=true)
void NotifyIntObjRemovedNoContactLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately=true)
void RefreshLayersNow ()
Member Function Documentation
void NotifyIntObjAddedInteractionLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately = true)
Referenced by InteractionManager.GetInteractionLayerMask().
void NotifyIntObjAddedNoContactLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately = true)
Referenced by InteractionManager.GetInteractionLayerMask().
void NotifyIntObjRemovedInteractionLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately = true)
Referenced by InteractionManager.GetInteractionLayerMask().
void NotifyIntObjRemovedNoContactLayer (IInteractionBehaviour intObj, int layer, bool refreshImmediately = true)
Referenced by InteractionManager.GetInteractionLayerMask().
void RefreshLayersNow ()
Referenced by InteractionManager.GetInteractionLayerMask().