Unity Modules: SupportInfo Struct Reference
SupportInfo Struct Reference
The support info class provides a very basic way to notify that something is fully supported, partially supported, or not supported. The struct contains a support type, which can be either Full, Warning, or Error. The struct also contains a message to give information about the support.
Public Member Functions
SupportInfo OrWorse (SupportInfo other)
Helper method that returns either the current support info struct, or the argument support info struct. The argument is only chosen as the return value if it has less support than the current support.
Static Public Member Functions
static SupportInfo FullSupport ()
Helper getter to return a struct that signifies full support.
static SupportInfo Warning (string message)
Helper getter to return a struct that signifies partial support with a warning message.
static SupportInfo Error (string message)
Helper getter to return a struct that signifies no support with an error message.
Public Attributes
SupportType support
string message
Detailed Description
The support info class provides a very basic way to notify that something is fully supported, partially supported, or not supported. The struct contains a support type, which can be either Full, Warning, or Error. The struct also contains a message to give information about the support.
Member Function Documentation
static SupportInfo Error (string message) static
Helper getter to return a struct that signifies no support with an error message.
Referenced by SupportInfo.Error(), LeapDynamicRenderer.GetSpaceSupportInfo(), LeapBakedRenderer.GetSpaceSupportInfo(), LeapBlendShapeFeature.GetSupportInfo(), CustomChannelFeatureBase< CustomVectorChannelData >.GetSupportInfo(), LeapMesherBase.GetSupportInfo(), and LeapGraphicGroup.RebuildFeatureSupportInfo().
static SupportInfo FullSupport () static
Helper getter to return a struct that signifies full support.
Referenced by LeapTextRenderer.GetSpaceSupportInfo(), LeapDynamicRenderer.GetSpaceSupportInfo(), LeapBakedRenderer.GetSpaceSupportInfo(), LeapBlendShapeFeature.GetSupportInfo(), CustomChannelFeatureBase< CustomVectorChannelData >.GetSupportInfo(), LeapGraphicFeatureBase.GetSupportInfo(), and LeapGraphicGroup.RebuildFeatureSupportInfo().
SupportInfo OrWorse (SupportInfo other)
Helper method that returns either the current support info struct, or the argument support info struct. The argument is only chosen as the return value if it has less support than the current support.
Referenced by LeapMesherBase.GetSupportInfo().
static SupportInfo Warning (string message) static
Helper getter to return a struct that signifies partial support with a warning message.
Referenced by SupportInfo.Warning().
Member Data Documentation
string message
SupportType support
Referenced by SupportInfo.OrWorse().