Unity Modules: Either< A, B > Struct Template Reference
Either< A, B > Struct Template Reference
A data structure that represents either a value of type A or a value of type B. The value can never be both A and B. Neither A nor B can ever be null.
Public Member Functions
Either (A a)
Constructs an Either with a value of A.
Either (B b)
Constructs an Either with a value of B.
void Match (Action< A > ifA, Action< B > ifB)
Calls the first delegate with the value of A if it is present, else calls the second delegate with the value of B.
bool TryGetA (out A a)
If this either contains the value of A, the out argument is filled with that value and this method returns true, else it returns false.
bool TryGetB (out B b)
If this either contains the value of B, the out argument is filled with that value and this method returns true, else it returns false.
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (Either< A, B > other)
int CompareTo (object obj)
int CompareTo (Either< A, B > other)
Static Public Member Functions
static bool operator== (Either< A, B > either0, Either< A, B > either1)
static bool operator!= (Either< A, B > either0, Either< A, B > either1)
static bool operator> (Either< A, B > either0, Either< A, B > either1)
static bool operator>= (Either< A, B > either0, Either< A, B > either1)
static bool operator< (Either< A, B > either0, Either< A, B > either1)
static bool operator<= (Either< A, B > either0, Either< A, B > either1)
static implicit operator Either< A, B > (A a)
static implicit operator Either< A, B > (B b)
Public Attributes
readonly bool isA
Returns whether or not this Either contains the first value.
Properties
bool isB [get]
Returns whether or not this Either contains the second value.
Maybe< A > a [get]
Returns a Maybe that contains the value of A if it exists, or no value if it doesn't.
Maybe< B > b [get]
Returns a Maybe that contains the value of B if it exists, or no value if it doesn't.
Detailed Description
A data structure that represents either a value of type A or a value of type B. The value can never be both A and B. Neither A nor B can ever be null.
Constructor & Destructor Documentation
Either (A a)
Constructs an Either with a value of A.
Either (B b)
Constructs an Either with a value of B.
Member Function Documentation
int CompareTo (object obj)
Referenced by Either< A, B >.operator<(), Either< A, B >.operator<=(), Either< A, B >.operator>(), and Either< A, B >.operator>=().
int CompareTo (Either< A, B > other)
override bool Equals (object obj)
Referenced by Either< A, B >.operator!=(), and Either< A, B >.operator==().
bool Equals (Either< A, B > other)
override int GetHashCode ()
void Match (Action< A > ifA, Action< B > ifB)
Calls the first delegate with the value of A if it is present, else calls the second delegate with the value of B.
static implicit operator Either< A, B > (A a) static
static implicit operator Either< A, B > (B b) static
static bool operator!= (Either< A, B > either0, Either< A, B > either1) static
static bool operator< (Either< A, B > either0, Either< A, B > either1) static
static bool operator<= (Either< A, B > either0, Either< A, B > either1) static
static bool operator== (Either< A, B > either0, Either< A, B > either1) static
static bool operator> (Either< A, B > either0, Either< A, B > either1) static
static bool operator>= (Either< A, B > either0, Either< A, B > either1) static
bool TryGetA (out A a)
If this either contains the value of A, the out argument is filled with that value and this method returns true, else it returns false.
bool TryGetB (out B b)
If this either contains the value of B, the out argument is filled with that value and this method returns true, else it returns false.
Member Data Documentation
readonly bool isA
Returns whether or not this Either contains the first value.
Referenced by Either< A, B >.CompareTo(), Either< A, B >.Equals(), Either< A, B >.TryGetA(), and Either< A, B >.TryGetB().
Property Documentation
Maybe<A> a get
Returns a Maybe that contains the value of A if it exists, or no value if it doesn't.
Referenced by Either< A, B >.Either(), and Either< A, B >.operator Either< A, B >().
Maybe<B> b get
Returns a Maybe that contains the value of B if it exists, or no value if it doesn't.
Referenced by Either< A, B >.Either(), and Either< A, B >.operator Either< A, B >().
bool isB get
Returns whether or not this Either contains the second value.