Unity Modules: Hash Struct Reference
Hash Struct Reference
Public Member Functions
Hash (int hash)
void Add< T > (T t)
void AddRange< T > (List< T > sequence)
IEnumerator GetEnumerator ()
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (Hash other)
Static Public Member Functions
static Hash GetHierarchyHash (Transform root)
static Hash GetDataHash (Transform transform)
Returns a hash of the Transform in addition to it's data. Changing either the position, rotation, or scale of a transform will result in a different hash. Two transforms with the same position rotation and scale will not have the same hash!
static implicit operator Hash (int hash)
static implicit operator int (Hash hash)
Constructor & Destructor Documentation
Hash (int hash)
Referenced by Hash.Equals(), Hash.GetDataHash(), and Hash.operator Hash().
Member Function Documentation
void Add< T > (T t)
void AddRange< T > (List< T > sequence)
override bool Equals (object obj)
bool Equals (Hash other)
static Hash GetDataHash (Transform transform) static
Returns a hash of the Transform in addition to it's data. Changing either the position, rotation, or scale of a transform will result in a different hash. Two transforms with the same position rotation and scale will not have the same hash!
Referenced by Hash.GetHierarchyHash().
IEnumerator GetEnumerator ()
override int GetHashCode ()
static Hash GetHierarchyHash (Transform root) static
static implicit operator Hash (int hash) static
static implicit operator int (Hash hash) static